#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planillas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PLANILLAS")]
	public partial class DBPlanillasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDEPARTAMENTO(DEPARTAMENTO instance);
    partial void UpdateDEPARTAMENTO(DEPARTAMENTO instance);
    partial void DeleteDEPARTAMENTO(DEPARTAMENTO instance);
    partial void InsertMUNICIPIO(MUNICIPIO instance);
    partial void UpdateMUNICIPIO(MUNICIPIO instance);
    partial void DeleteMUNICIPIO(MUNICIPIO instance);
    partial void InsertPAIS(PAIS instance);
    partial void UpdatePAIS(PAIS instance);
    partial void DeletePAIS(PAIS instance);
    partial void InsertTIPO_EMPLEADO(TIPO_EMPLEADO instance);
    partial void UpdateTIPO_EMPLEADO(TIPO_EMPLEADO instance);
    partial void DeleteTIPO_EMPLEADO(TIPO_EMPLEADO instance);
    partial void InsertAREA(AREA instance);
    partial void UpdateAREA(AREA instance);
    partial void DeleteAREA(AREA instance);
    partial void InsertTRASLADO(TRASLADO instance);
    partial void UpdateTRASLADO(TRASLADO instance);
    partial void DeleteTRASLADO(TRASLADO instance);
    partial void InsertEMPLEADO(EMPLEADO instance);
    partial void UpdateEMPLEADO(EMPLEADO instance);
    partial void DeleteEMPLEADO(EMPLEADO instance);
    #endregion
		
		public DBPlanillasDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PLANILLASConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBPlanillasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPlanillasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPlanillasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPlanillasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DEPARTAMENTO> DEPARTAMENTO
		{
			get
			{
				return this.GetTable<DEPARTAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<MUNICIPIO> MUNICIPIO
		{
			get
			{
				return this.GetTable<MUNICIPIO>();
			}
		}
		
		public System.Data.Linq.Table<PAIS> PAIS
		{
			get
			{
				return this.GetTable<PAIS>();
			}
		}
		
		public System.Data.Linq.Table<TIPO_EMPLEADO> TIPO_EMPLEADO
		{
			get
			{
				return this.GetTable<TIPO_EMPLEADO>();
			}
		}
		
		public System.Data.Linq.Table<AREA> AREA
		{
			get
			{
				return this.GetTable<AREA>();
			}
		}
		
		public System.Data.Linq.Table<TRASLADO> TRASLADO
		{
			get
			{
				return this.GetTable<TRASLADO>();
			}
		}
		
		public System.Data.Linq.Table<EMPLEADO> EMPLEADO
		{
			get
			{
				return this.GetTable<EMPLEADO>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MTTO_AREAS")]
		public int SP_MTTO_AREAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_AREA", DbType="Int")] System.Nullable<int> cODIGO_AREA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_AREA", DbType="VarChar(50)")] string nOMBRE_AREA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_MODIFICADOR", DbType="Int")] System.Nullable<int> tIPO_MODIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_AREA, nOMBRE_AREA, tIPO_MODIFICADOR);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MTTO_TIPO_EMPLEADO")]
		public int SP_MTTO_TIPO_EMPLEADO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_TIPO_EMPLEADO", DbType="Int")] System.Nullable<int> cODIGO_TIPO_EMPLEADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_TIPO_EMPLEADO", DbType="VarChar(30)")] string nOMBRE_TIPO_EMPLEADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUELDO", DbType="Decimal(12,2)")] System.Nullable<decimal> sUELDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_MODIFICADOR", DbType="Int")] System.Nullable<int> tIPO_MODIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_TIPO_EMPLEADO, nOMBRE_TIPO_EMPLEADO, sUELDO, tIPO_MODIFICADOR);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPARTAMENTO")]
	public partial class DEPARTAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_DEPARTAMENTO;
		
		private string _NOMBRE_DEPARTAMENTO;
		
		private int _PAIS;
		
		private EntitySet<MUNICIPIO> _MUNICIPIO;
		
		private EntitySet<EMPLEADO> _EMPLEADO;
		
		private EntityRef<PAIS> _PAIS1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_DEPARTAMENTOChanging(int value);
    partial void OnCODIGO_DEPARTAMENTOChanged();
    partial void OnNOMBRE_DEPARTAMENTOChanging(string value);
    partial void OnNOMBRE_DEPARTAMENTOChanged();
    partial void OnPAISChanging(int value);
    partial void OnPAISChanged();
    #endregion
		
		public DEPARTAMENTO()
		{
			this._MUNICIPIO = new EntitySet<MUNICIPIO>(new Action<MUNICIPIO>(this.attach_MUNICIPIO), new Action<MUNICIPIO>(this.detach_MUNICIPIO));
			this._EMPLEADO = new EntitySet<EMPLEADO>(new Action<EMPLEADO>(this.attach_EMPLEADO), new Action<EMPLEADO>(this.detach_EMPLEADO));
			this._PAIS1 = default(EntityRef<PAIS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_DEPARTAMENTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_DEPARTAMENTO
		{
			get
			{
				return this._CODIGO_DEPARTAMENTO;
			}
			set
			{
				if ((this._CODIGO_DEPARTAMENTO != value))
				{
					this.OnCODIGO_DEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_DEPARTAMENTO = value;
					this.SendPropertyChanged("CODIGO_DEPARTAMENTO");
					this.OnCODIGO_DEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DEPARTAMENTO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_DEPARTAMENTO
		{
			get
			{
				return this._NOMBRE_DEPARTAMENTO;
			}
			set
			{
				if ((this._NOMBRE_DEPARTAMENTO != value))
				{
					this.OnNOMBRE_DEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_DEPARTAMENTO = value;
					this.SendPropertyChanged("NOMBRE_DEPARTAMENTO");
					this.OnNOMBRE_DEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS", DbType="Int NOT NULL")]
		public int PAIS
		{
			get
			{
				return this._PAIS;
			}
			set
			{
				if ((this._PAIS != value))
				{
					if (this._PAIS1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAISChanging(value);
					this.SendPropertyChanging();
					this._PAIS = value;
					this.SendPropertyChanged("PAIS");
					this.OnPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTAMENTO_MUNICIPIO", Storage="_MUNICIPIO", ThisKey="CODIGO_DEPARTAMENTO", OtherKey="DEPARTAMENTO")]
		public EntitySet<MUNICIPIO> MUNICIPIO
		{
			get
			{
				return this._MUNICIPIO;
			}
			set
			{
				this._MUNICIPIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTAMENTO_EMPLEADO", Storage="_EMPLEADO", ThisKey="CODIGO_DEPARTAMENTO", OtherKey="DEPARTAMENTO")]
		public EntitySet<EMPLEADO> EMPLEADO
		{
			get
			{
				return this._EMPLEADO;
			}
			set
			{
				this._EMPLEADO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_DEPARTAMENTO", Storage="_PAIS1", ThisKey="PAIS", OtherKey="CODIGO_PAIS", IsForeignKey=true)]
		public PAIS PAIS1
		{
			get
			{
				return this._PAIS1.Entity;
			}
			set
			{
				PAIS previousValue = this._PAIS1.Entity;
				if (((previousValue != value) 
							|| (this._PAIS1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PAIS1.Entity = null;
						previousValue.DEPARTAMENTO.Remove(this);
					}
					this._PAIS1.Entity = value;
					if ((value != null))
					{
						value.DEPARTAMENTO.Add(this);
						this._PAIS = value.CODIGO_PAIS;
					}
					else
					{
						this._PAIS = default(int);
					}
					this.SendPropertyChanged("PAIS1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MUNICIPIO(MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTAMENTO1 = this;
		}
		
		private void detach_MUNICIPIO(MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTAMENTO1 = null;
		}
		
		private void attach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTAMENTO1 = this;
		}
		
		private void detach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTAMENTO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MUNICIPIO")]
	public partial class MUNICIPIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_MUNICIPIO;
		
		private string _NOMBRE_MINICIPIO;
		
		private int _PAIS;
		
		private int _DEPARTAMENTO;
		
		private EntitySet<EMPLEADO> _EMPLEADO;
		
		private EntityRef<DEPARTAMENTO> _DEPARTAMENTO1;
		
		private EntityRef<PAIS> _PAIS1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_MUNICIPIOChanging(int value);
    partial void OnCODIGO_MUNICIPIOChanged();
    partial void OnNOMBRE_MINICIPIOChanging(string value);
    partial void OnNOMBRE_MINICIPIOChanged();
    partial void OnPAISChanging(int value);
    partial void OnPAISChanged();
    partial void OnDEPARTAMENTOChanging(int value);
    partial void OnDEPARTAMENTOChanged();
    #endregion
		
		public MUNICIPIO()
		{
			this._EMPLEADO = new EntitySet<EMPLEADO>(new Action<EMPLEADO>(this.attach_EMPLEADO), new Action<EMPLEADO>(this.detach_EMPLEADO));
			this._DEPARTAMENTO1 = default(EntityRef<DEPARTAMENTO>);
			this._PAIS1 = default(EntityRef<PAIS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_MUNICIPIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_MUNICIPIO
		{
			get
			{
				return this._CODIGO_MUNICIPIO;
			}
			set
			{
				if ((this._CODIGO_MUNICIPIO != value))
				{
					this.OnCODIGO_MUNICIPIOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_MUNICIPIO = value;
					this.SendPropertyChanged("CODIGO_MUNICIPIO");
					this.OnCODIGO_MUNICIPIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MINICIPIO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MINICIPIO
		{
			get
			{
				return this._NOMBRE_MINICIPIO;
			}
			set
			{
				if ((this._NOMBRE_MINICIPIO != value))
				{
					this.OnNOMBRE_MINICIPIOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_MINICIPIO = value;
					this.SendPropertyChanged("NOMBRE_MINICIPIO");
					this.OnNOMBRE_MINICIPIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS", DbType="Int NOT NULL")]
		public int PAIS
		{
			get
			{
				return this._PAIS;
			}
			set
			{
				if ((this._PAIS != value))
				{
					if (this._PAIS1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAISChanging(value);
					this.SendPropertyChanging();
					this._PAIS = value;
					this.SendPropertyChanged("PAIS");
					this.OnPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTAMENTO", DbType="Int NOT NULL")]
		public int DEPARTAMENTO
		{
			get
			{
				return this._DEPARTAMENTO;
			}
			set
			{
				if ((this._DEPARTAMENTO != value))
				{
					if (this._DEPARTAMENTO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._DEPARTAMENTO = value;
					this.SendPropertyChanged("DEPARTAMENTO");
					this.OnDEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MUNICIPIO_EMPLEADO", Storage="_EMPLEADO", ThisKey="CODIGO_MUNICIPIO", OtherKey="MUNICIPIO")]
		public EntitySet<EMPLEADO> EMPLEADO
		{
			get
			{
				return this._EMPLEADO;
			}
			set
			{
				this._EMPLEADO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTAMENTO_MUNICIPIO", Storage="_DEPARTAMENTO1", ThisKey="DEPARTAMENTO", OtherKey="CODIGO_DEPARTAMENTO", IsForeignKey=true)]
		public DEPARTAMENTO DEPARTAMENTO1
		{
			get
			{
				return this._DEPARTAMENTO1.Entity;
			}
			set
			{
				DEPARTAMENTO previousValue = this._DEPARTAMENTO1.Entity;
				if (((previousValue != value) 
							|| (this._DEPARTAMENTO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DEPARTAMENTO1.Entity = null;
						previousValue.MUNICIPIO.Remove(this);
					}
					this._DEPARTAMENTO1.Entity = value;
					if ((value != null))
					{
						value.MUNICIPIO.Add(this);
						this._DEPARTAMENTO = value.CODIGO_DEPARTAMENTO;
					}
					else
					{
						this._DEPARTAMENTO = default(int);
					}
					this.SendPropertyChanged("DEPARTAMENTO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_MUNICIPIO", Storage="_PAIS1", ThisKey="PAIS", OtherKey="CODIGO_PAIS", IsForeignKey=true)]
		public PAIS PAIS1
		{
			get
			{
				return this._PAIS1.Entity;
			}
			set
			{
				PAIS previousValue = this._PAIS1.Entity;
				if (((previousValue != value) 
							|| (this._PAIS1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PAIS1.Entity = null;
						previousValue.MUNICIPIO.Remove(this);
					}
					this._PAIS1.Entity = value;
					if ((value != null))
					{
						value.MUNICIPIO.Add(this);
						this._PAIS = value.CODIGO_PAIS;
					}
					else
					{
						this._PAIS = default(int);
					}
					this.SendPropertyChanged("PAIS1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.MUNICIPIO1 = this;
		}
		
		private void detach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.MUNICIPIO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAIS")]
	public partial class PAIS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_PAIS;
		
		private string _NOMBRE_PAIS;
		
		private EntitySet<DEPARTAMENTO> _DEPARTAMENTO;
		
		private EntitySet<MUNICIPIO> _MUNICIPIO;
		
		private EntitySet<EMPLEADO> _EMPLEADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_PAISChanging(int value);
    partial void OnCODIGO_PAISChanged();
    partial void OnNOMBRE_PAISChanging(string value);
    partial void OnNOMBRE_PAISChanged();
    #endregion
		
		public PAIS()
		{
			this._DEPARTAMENTO = new EntitySet<DEPARTAMENTO>(new Action<DEPARTAMENTO>(this.attach_DEPARTAMENTO), new Action<DEPARTAMENTO>(this.detach_DEPARTAMENTO));
			this._MUNICIPIO = new EntitySet<MUNICIPIO>(new Action<MUNICIPIO>(this.attach_MUNICIPIO), new Action<MUNICIPIO>(this.detach_MUNICIPIO));
			this._EMPLEADO = new EntitySet<EMPLEADO>(new Action<EMPLEADO>(this.attach_EMPLEADO), new Action<EMPLEADO>(this.detach_EMPLEADO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PAIS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_PAIS
		{
			get
			{
				return this._CODIGO_PAIS;
			}
			set
			{
				if ((this._CODIGO_PAIS != value))
				{
					this.OnCODIGO_PAISChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_PAIS = value;
					this.SendPropertyChanged("CODIGO_PAIS");
					this.OnCODIGO_PAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PAIS", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string NOMBRE_PAIS
		{
			get
			{
				return this._NOMBRE_PAIS;
			}
			set
			{
				if ((this._NOMBRE_PAIS != value))
				{
					this.OnNOMBRE_PAISChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_PAIS = value;
					this.SendPropertyChanged("NOMBRE_PAIS");
					this.OnNOMBRE_PAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_DEPARTAMENTO", Storage="_DEPARTAMENTO", ThisKey="CODIGO_PAIS", OtherKey="PAIS")]
		public EntitySet<DEPARTAMENTO> DEPARTAMENTO
		{
			get
			{
				return this._DEPARTAMENTO;
			}
			set
			{
				this._DEPARTAMENTO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_MUNICIPIO", Storage="_MUNICIPIO", ThisKey="CODIGO_PAIS", OtherKey="PAIS")]
		public EntitySet<MUNICIPIO> MUNICIPIO
		{
			get
			{
				return this._MUNICIPIO;
			}
			set
			{
				this._MUNICIPIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_EMPLEADO", Storage="_EMPLEADO", ThisKey="CODIGO_PAIS", OtherKey="PAIS")]
		public EntitySet<EMPLEADO> EMPLEADO
		{
			get
			{
				return this._EMPLEADO;
			}
			set
			{
				this._EMPLEADO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DEPARTAMENTO(DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = this;
		}
		
		private void detach_DEPARTAMENTO(DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = null;
		}
		
		private void attach_MUNICIPIO(MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = this;
		}
		
		private void detach_MUNICIPIO(MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = null;
		}
		
		private void attach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = this;
		}
		
		private void detach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIPO_EMPLEADO")]
	public partial class TIPO_EMPLEADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_TIPO_EMPLEADO;
		
		private string _NOMBRE_TIPO_EMPLEADO;
		
		private decimal _SUELDO;
		
		private EntitySet<EMPLEADO> _EMPLEADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_TIPO_EMPLEADOChanging(int value);
    partial void OnCODIGO_TIPO_EMPLEADOChanged();
    partial void OnNOMBRE_TIPO_EMPLEADOChanging(string value);
    partial void OnNOMBRE_TIPO_EMPLEADOChanged();
    partial void OnSUELDOChanging(decimal value);
    partial void OnSUELDOChanged();
    #endregion
		
		public TIPO_EMPLEADO()
		{
			this._EMPLEADO = new EntitySet<EMPLEADO>(new Action<EMPLEADO>(this.attach_EMPLEADO), new Action<EMPLEADO>(this.detach_EMPLEADO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TIPO_EMPLEADO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_TIPO_EMPLEADO
		{
			get
			{
				return this._CODIGO_TIPO_EMPLEADO;
			}
			set
			{
				if ((this._CODIGO_TIPO_EMPLEADO != value))
				{
					this.OnCODIGO_TIPO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_TIPO_EMPLEADO = value;
					this.SendPropertyChanged("CODIGO_TIPO_EMPLEADO");
					this.OnCODIGO_TIPO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_TIPO_EMPLEADO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_TIPO_EMPLEADO
		{
			get
			{
				return this._NOMBRE_TIPO_EMPLEADO;
			}
			set
			{
				if ((this._NOMBRE_TIPO_EMPLEADO != value))
				{
					this.OnNOMBRE_TIPO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_TIPO_EMPLEADO = value;
					this.SendPropertyChanged("NOMBRE_TIPO_EMPLEADO");
					this.OnNOMBRE_TIPO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUELDO", DbType="Decimal(12,2) NOT NULL")]
		public decimal SUELDO
		{
			get
			{
				return this._SUELDO;
			}
			set
			{
				if ((this._SUELDO != value))
				{
					this.OnSUELDOChanging(value);
					this.SendPropertyChanging();
					this._SUELDO = value;
					this.SendPropertyChanged("SUELDO");
					this.OnSUELDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPO_EMPLEADO_EMPLEADO", Storage="_EMPLEADO", ThisKey="CODIGO_TIPO_EMPLEADO", OtherKey="TIPO_EMPLEADO")]
		public EntitySet<EMPLEADO> EMPLEADO
		{
			get
			{
				return this._EMPLEADO;
			}
			set
			{
				this._EMPLEADO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.TIPO_EMPLEADO1 = this;
		}
		
		private void detach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.TIPO_EMPLEADO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AREA")]
	public partial class AREA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_AREA;
		
		private string _NOMBRE_AREA;
		
		private EntitySet<TRASLADO> _TRASLADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_AREAChanging(int value);
    partial void OnCODIGO_AREAChanged();
    partial void OnNOMBRE_AREAChanging(string value);
    partial void OnNOMBRE_AREAChanged();
    #endregion
		
		public AREA()
		{
			this._TRASLADO = new EntitySet<TRASLADO>(new Action<TRASLADO>(this.attach_TRASLADO), new Action<TRASLADO>(this.detach_TRASLADO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_AREA
		{
			get
			{
				return this._CODIGO_AREA;
			}
			set
			{
				if ((this._CODIGO_AREA != value))
				{
					this.OnCODIGO_AREAChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_AREA = value;
					this.SendPropertyChanged("CODIGO_AREA");
					this.OnCODIGO_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_AREA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_AREA
		{
			get
			{
				return this._NOMBRE_AREA;
			}
			set
			{
				if ((this._NOMBRE_AREA != value))
				{
					this.OnNOMBRE_AREAChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_AREA = value;
					this.SendPropertyChanged("NOMBRE_AREA");
					this.OnNOMBRE_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AREA_TRASLADO", Storage="_TRASLADO", ThisKey="CODIGO_AREA", OtherKey="CODIGO_AREA")]
		public EntitySet<TRASLADO> TRASLADO
		{
			get
			{
				return this._TRASLADO;
			}
			set
			{
				this._TRASLADO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRASLADO(TRASLADO entity)
		{
			this.SendPropertyChanging();
			entity.AREA = this;
		}
		
		private void detach_TRASLADO(TRASLADO entity)
		{
			this.SendPropertyChanging();
			entity.AREA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRASLADO")]
	public partial class TRASLADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_TRASLADOS;
		
		private int _CODIGO_EMPLEADO;
		
		private int _CODIGO_AREA;
		
		private string _ESTADO_TRASLADO;
		
		private System.DateTime _FECHA_TRASLADO;
		
		private System.DateTime _USUARIO_CREA;
		
		private System.DateTime _FECHA_CREA;
		
		private string _USUARIO_ACTUALIZA;
		
		private System.DateTime _FECHA_ACTUALIZA;
		
		private EntityRef<AREA> _AREA;
		
		private EntityRef<EMPLEADO> _EMPLEADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_TRASLADOSChanging(int value);
    partial void OnCODIGO_TRASLADOSChanged();
    partial void OnCODIGO_EMPLEADOChanging(int value);
    partial void OnCODIGO_EMPLEADOChanged();
    partial void OnCODIGO_AREAChanging(int value);
    partial void OnCODIGO_AREAChanged();
    partial void OnESTADO_TRASLADOChanging(string value);
    partial void OnESTADO_TRASLADOChanged();
    partial void OnFECHA_TRASLADOChanging(System.DateTime value);
    partial void OnFECHA_TRASLADOChanged();
    partial void OnUSUARIO_CREAChanging(System.DateTime value);
    partial void OnUSUARIO_CREAChanged();
    partial void OnFECHA_CREAChanging(System.DateTime value);
    partial void OnFECHA_CREAChanged();
    partial void OnUSUARIO_ACTUALIZAChanging(string value);
    partial void OnUSUARIO_ACTUALIZAChanged();
    partial void OnFECHA_ACTUALIZAChanging(System.DateTime value);
    partial void OnFECHA_ACTUALIZAChanged();
    #endregion
		
		public TRASLADO()
		{
			this._AREA = default(EntityRef<AREA>);
			this._EMPLEADO = default(EntityRef<EMPLEADO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TRASLADOS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_TRASLADOS
		{
			get
			{
				return this._CODIGO_TRASLADOS;
			}
			set
			{
				if ((this._CODIGO_TRASLADOS != value))
				{
					if (this._EMPLEADO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGO_TRASLADOSChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_TRASLADOS = value;
					this.SendPropertyChanged("CODIGO_TRASLADOS");
					this.OnCODIGO_TRASLADOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_EMPLEADO", DbType="Int NOT NULL")]
		public int CODIGO_EMPLEADO
		{
			get
			{
				return this._CODIGO_EMPLEADO;
			}
			set
			{
				if ((this._CODIGO_EMPLEADO != value))
				{
					this.OnCODIGO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_EMPLEADO = value;
					this.SendPropertyChanged("CODIGO_EMPLEADO");
					this.OnCODIGO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA", DbType="Int NOT NULL")]
		public int CODIGO_AREA
		{
			get
			{
				return this._CODIGO_AREA;
			}
			set
			{
				if ((this._CODIGO_AREA != value))
				{
					if (this._AREA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODIGO_AREAChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_AREA = value;
					this.SendPropertyChanged("CODIGO_AREA");
					this.OnCODIGO_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_TRASLADO", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ESTADO_TRASLADO
		{
			get
			{
				return this._ESTADO_TRASLADO;
			}
			set
			{
				if ((this._ESTADO_TRASLADO != value))
				{
					this.OnESTADO_TRASLADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_TRASLADO = value;
					this.SendPropertyChanged("ESTADO_TRASLADO");
					this.OnESTADO_TRASLADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TRASLADO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_TRASLADO
		{
			get
			{
				return this._FECHA_TRASLADO;
			}
			set
			{
				if ((this._FECHA_TRASLADO != value))
				{
					this.OnFECHA_TRASLADOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_TRASLADO = value;
					this.SendPropertyChanged("FECHA_TRASLADO");
					this.OnFECHA_TRASLADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_CREA", DbType="DateTime NOT NULL")]
		public System.DateTime USUARIO_CREA
		{
			get
			{
				return this._USUARIO_CREA;
			}
			set
			{
				if ((this._USUARIO_CREA != value))
				{
					this.OnUSUARIO_CREAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_CREA = value;
					this.SendPropertyChanged("USUARIO_CREA");
					this.OnUSUARIO_CREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CREA
		{
			get
			{
				return this._FECHA_CREA;
			}
			set
			{
				if ((this._FECHA_CREA != value))
				{
					this.OnFECHA_CREAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CREA = value;
					this.SendPropertyChanged("FECHA_CREA");
					this.OnFECHA_CREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ACTUALIZA", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USUARIO_ACTUALIZA
		{
			get
			{
				return this._USUARIO_ACTUALIZA;
			}
			set
			{
				if ((this._USUARIO_ACTUALIZA != value))
				{
					this.OnUSUARIO_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_ACTUALIZA = value;
					this.SendPropertyChanged("USUARIO_ACTUALIZA");
					this.OnUSUARIO_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ACTUALIZA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_ACTUALIZA
		{
			get
			{
				return this._FECHA_ACTUALIZA;
			}
			set
			{
				if ((this._FECHA_ACTUALIZA != value))
				{
					this.OnFECHA_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ACTUALIZA = value;
					this.SendPropertyChanged("FECHA_ACTUALIZA");
					this.OnFECHA_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AREA_TRASLADO", Storage="_AREA", ThisKey="CODIGO_AREA", OtherKey="CODIGO_AREA", IsForeignKey=true)]
		public AREA AREA
		{
			get
			{
				return this._AREA.Entity;
			}
			set
			{
				AREA previousValue = this._AREA.Entity;
				if (((previousValue != value) 
							|| (this._AREA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AREA.Entity = null;
						previousValue.TRASLADO.Remove(this);
					}
					this._AREA.Entity = value;
					if ((value != null))
					{
						value.TRASLADO.Add(this);
						this._CODIGO_AREA = value.CODIGO_AREA;
					}
					else
					{
						this._CODIGO_AREA = default(int);
					}
					this.SendPropertyChanged("AREA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EMPLEADO_TRASLADO", Storage="_EMPLEADO", ThisKey="CODIGO_TRASLADOS", OtherKey="CODIGO_EMPLEADO", IsForeignKey=true)]
		public EMPLEADO EMPLEADO
		{
			get
			{
				return this._EMPLEADO.Entity;
			}
			set
			{
				EMPLEADO previousValue = this._EMPLEADO.Entity;
				if (((previousValue != value) 
							|| (this._EMPLEADO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EMPLEADO.Entity = null;
						previousValue.TRASLADO = null;
					}
					this._EMPLEADO.Entity = value;
					if ((value != null))
					{
						value.TRASLADO = this;
						this._CODIGO_TRASLADOS = value.CODIGO_EMPLEADO;
					}
					else
					{
						this._CODIGO_TRASLADOS = default(int);
					}
					this.SendPropertyChanged("EMPLEADO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPLEADO")]
	public partial class EMPLEADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_EMPLEADO;
		
		private string _PRIMER_NOMBRE;
		
		private string _SEGUNDO_NOMBRE;
		
		private string _PRIMER_APELLIDO;
		
		private string _SEGUNDO_APELLIDO;
		
		private System.DateTime _FECHA_NACIMIENTO;
		
		private char _SEXO;
		
		private int _PAIS;
		
		private int _DEPARTAMENTO;
		
		private int _MUNICIPIO;
		
		private string _DIRECCION;
		
		private string _ESTADO_CIVIL;
		
		private string _TELEFONO;
		
		private string _CORREO_ELECTRONICO;
		
		private string _LUGAR_NACIMIENTO;
		
		private string _DUI;
		
		private string _NIT;
		
		private string _AFP;
		
		private string _SEGURO;
		
		private string _NUP;
		
		private int _TIPO_EMPLEADO;
		
		private System.DateTime _FECHA_INGRESO;
		
		private System.DateTime _FECHA_RETIRO;
		
		private string _USUARIO_CREA;
		
		private System.DateTime _FECHA_CREA;
		
		private string _USUARIO_ACTUALIZA;
		
		private System.Nullable<System.DateTime> _FECHA_ACTUALIZA;
		
		private bool _ACTIVO;
		
		private EntityRef<TRASLADO> _TRASLADO;
		
		private EntityRef<DEPARTAMENTO> _DEPARTAMENTO1;
		
		private EntityRef<MUNICIPIO> _MUNICIPIO1;
		
		private EntityRef<PAIS> _PAIS1;
		
		private EntityRef<TIPO_EMPLEADO> _TIPO_EMPLEADO1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_EMPLEADOChanging(int value);
    partial void OnCODIGO_EMPLEADOChanged();
    partial void OnPRIMER_NOMBREChanging(string value);
    partial void OnPRIMER_NOMBREChanged();
    partial void OnSEGUNDO_NOMBREChanging(string value);
    partial void OnSEGUNDO_NOMBREChanged();
    partial void OnPRIMER_APELLIDOChanging(string value);
    partial void OnPRIMER_APELLIDOChanged();
    partial void OnSEGUNDO_APELLIDOChanging(string value);
    partial void OnSEGUNDO_APELLIDOChanged();
    partial void OnFECHA_NACIMIENTOChanging(System.DateTime value);
    partial void OnFECHA_NACIMIENTOChanged();
    partial void OnSEXOChanging(char value);
    partial void OnSEXOChanged();
    partial void OnPAISChanging(int value);
    partial void OnPAISChanged();
    partial void OnDEPARTAMENTOChanging(int value);
    partial void OnDEPARTAMENTOChanged();
    partial void OnMUNICIPIOChanging(int value);
    partial void OnMUNICIPIOChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnESTADO_CIVILChanging(string value);
    partial void OnESTADO_CIVILChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnCORREO_ELECTRONICOChanging(string value);
    partial void OnCORREO_ELECTRONICOChanged();
    partial void OnLUGAR_NACIMIENTOChanging(string value);
    partial void OnLUGAR_NACIMIENTOChanged();
    partial void OnDUIChanging(string value);
    partial void OnDUIChanged();
    partial void OnNITChanging(string value);
    partial void OnNITChanged();
    partial void OnAFPChanging(string value);
    partial void OnAFPChanged();
    partial void OnSEGUROChanging(string value);
    partial void OnSEGUROChanged();
    partial void OnNUPChanging(string value);
    partial void OnNUPChanged();
    partial void OnTIPO_EMPLEADOChanging(int value);
    partial void OnTIPO_EMPLEADOChanged();
    partial void OnFECHA_INGRESOChanging(System.DateTime value);
    partial void OnFECHA_INGRESOChanged();
    partial void OnFECHA_RETIROChanging(System.DateTime value);
    partial void OnFECHA_RETIROChanged();
    partial void OnUSUARIO_CREAChanging(string value);
    partial void OnUSUARIO_CREAChanged();
    partial void OnFECHA_CREAChanging(System.DateTime value);
    partial void OnFECHA_CREAChanged();
    partial void OnUSUARIO_ACTUALIZAChanging(string value);
    partial void OnUSUARIO_ACTUALIZAChanged();
    partial void OnFECHA_ACTUALIZAChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_ACTUALIZAChanged();
    partial void OnACTIVOChanging(bool value);
    partial void OnACTIVOChanged();
    #endregion
		
		public EMPLEADO()
		{
			this._TRASLADO = default(EntityRef<TRASLADO>);
			this._DEPARTAMENTO1 = default(EntityRef<DEPARTAMENTO>);
			this._MUNICIPIO1 = default(EntityRef<MUNICIPIO>);
			this._PAIS1 = default(EntityRef<PAIS>);
			this._TIPO_EMPLEADO1 = default(EntityRef<TIPO_EMPLEADO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_EMPLEADO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_EMPLEADO
		{
			get
			{
				return this._CODIGO_EMPLEADO;
			}
			set
			{
				if ((this._CODIGO_EMPLEADO != value))
				{
					this.OnCODIGO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_EMPLEADO = value;
					this.SendPropertyChanged("CODIGO_EMPLEADO");
					this.OnCODIGO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMER_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PRIMER_NOMBRE
		{
			get
			{
				return this._PRIMER_NOMBRE;
			}
			set
			{
				if ((this._PRIMER_NOMBRE != value))
				{
					this.OnPRIMER_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._PRIMER_NOMBRE = value;
					this.SendPropertyChanged("PRIMER_NOMBRE");
					this.OnPRIMER_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGUNDO_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SEGUNDO_NOMBRE
		{
			get
			{
				return this._SEGUNDO_NOMBRE;
			}
			set
			{
				if ((this._SEGUNDO_NOMBRE != value))
				{
					this.OnSEGUNDO_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._SEGUNDO_NOMBRE = value;
					this.SendPropertyChanged("SEGUNDO_NOMBRE");
					this.OnSEGUNDO_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMER_APELLIDO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PRIMER_APELLIDO
		{
			get
			{
				return this._PRIMER_APELLIDO;
			}
			set
			{
				if ((this._PRIMER_APELLIDO != value))
				{
					this.OnPRIMER_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._PRIMER_APELLIDO = value;
					this.SendPropertyChanged("PRIMER_APELLIDO");
					this.OnPRIMER_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGUNDO_APELLIDO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SEGUNDO_APELLIDO
		{
			get
			{
				return this._SEGUNDO_APELLIDO;
			}
			set
			{
				if ((this._SEGUNDO_APELLIDO != value))
				{
					this.OnSEGUNDO_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._SEGUNDO_APELLIDO = value;
					this.SendPropertyChanged("SEGUNDO_APELLIDO");
					this.OnSEGUNDO_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this.OnFECHA_NACIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_NACIMIENTO = value;
					this.SendPropertyChanged("FECHA_NACIMIENTO");
					this.OnFECHA_NACIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="Char(1) NOT NULL")]
		public char SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this.OnSEXOChanging(value);
					this.SendPropertyChanging();
					this._SEXO = value;
					this.SendPropertyChanged("SEXO");
					this.OnSEXOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS", DbType="Int NOT NULL")]
		public int PAIS
		{
			get
			{
				return this._PAIS;
			}
			set
			{
				if ((this._PAIS != value))
				{
					if (this._PAIS1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAISChanging(value);
					this.SendPropertyChanging();
					this._PAIS = value;
					this.SendPropertyChanged("PAIS");
					this.OnPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTAMENTO", DbType="Int NOT NULL")]
		public int DEPARTAMENTO
		{
			get
			{
				return this._DEPARTAMENTO;
			}
			set
			{
				if ((this._DEPARTAMENTO != value))
				{
					if (this._DEPARTAMENTO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._DEPARTAMENTO = value;
					this.SendPropertyChanged("DEPARTAMENTO");
					this.OnDEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUNICIPIO", DbType="Int NOT NULL")]
		public int MUNICIPIO
		{
			get
			{
				return this._MUNICIPIO;
			}
			set
			{
				if ((this._MUNICIPIO != value))
				{
					if (this._MUNICIPIO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMUNICIPIOChanging(value);
					this.SendPropertyChanging();
					this._MUNICIPIO = value;
					this.SendPropertyChanged("MUNICIPIO");
					this.OnMUNICIPIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(250)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_CIVIL", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ESTADO_CIVIL
		{
			get
			{
				return this._ESTADO_CIVIL;
			}
			set
			{
				if ((this._ESTADO_CIVIL != value))
				{
					this.OnESTADO_CIVILChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_CIVIL = value;
					this.SendPropertyChanged("ESTADO_CIVIL");
					this.OnESTADO_CIVILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this.OnCORREO_ELECTRONICOChanging(value);
					this.SendPropertyChanging();
					this._CORREO_ELECTRONICO = value;
					this.SendPropertyChanged("CORREO_ELECTRONICO");
					this.OnCORREO_ELECTRONICOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUGAR_NACIMIENTO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LUGAR_NACIMIENTO
		{
			get
			{
				return this._LUGAR_NACIMIENTO;
			}
			set
			{
				if ((this._LUGAR_NACIMIENTO != value))
				{
					this.OnLUGAR_NACIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._LUGAR_NACIMIENTO = value;
					this.SendPropertyChanged("LUGAR_NACIMIENTO");
					this.OnLUGAR_NACIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DUI
		{
			get
			{
				return this._DUI;
			}
			set
			{
				if ((this._DUI != value))
				{
					this.OnDUIChanging(value);
					this.SendPropertyChanging();
					this._DUI = value;
					this.SendPropertyChanged("DUI");
					this.OnDUIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this.OnNITChanging(value);
					this.SendPropertyChanging();
					this._NIT = value;
					this.SendPropertyChanged("NIT");
					this.OnNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AFP", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string AFP
		{
			get
			{
				return this._AFP;
			}
			set
			{
				if ((this._AFP != value))
				{
					this.OnAFPChanging(value);
					this.SendPropertyChanging();
					this._AFP = value;
					this.SendPropertyChanged("AFP");
					this.OnAFPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGURO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SEGURO
		{
			get
			{
				return this._SEGURO;
			}
			set
			{
				if ((this._SEGURO != value))
				{
					this.OnSEGUROChanging(value);
					this.SendPropertyChanging();
					this._SEGURO = value;
					this.SendPropertyChanged("SEGURO");
					this.OnSEGUROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUP", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NUP
		{
			get
			{
				return this._NUP;
			}
			set
			{
				if ((this._NUP != value))
				{
					this.OnNUPChanging(value);
					this.SendPropertyChanging();
					this._NUP = value;
					this.SendPropertyChanged("NUP");
					this.OnNUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_EMPLEADO", DbType="Int NOT NULL")]
		public int TIPO_EMPLEADO
		{
			get
			{
				return this._TIPO_EMPLEADO;
			}
			set
			{
				if ((this._TIPO_EMPLEADO != value))
				{
					if (this._TIPO_EMPLEADO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTIPO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._TIPO_EMPLEADO = value;
					this.SendPropertyChanged("TIPO_EMPLEADO");
					this.OnTIPO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INGRESO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_INGRESO
		{
			get
			{
				return this._FECHA_INGRESO;
			}
			set
			{
				if ((this._FECHA_INGRESO != value))
				{
					this.OnFECHA_INGRESOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INGRESO = value;
					this.SendPropertyChanged("FECHA_INGRESO");
					this.OnFECHA_INGRESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_RETIRO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_RETIRO
		{
			get
			{
				return this._FECHA_RETIRO;
			}
			set
			{
				if ((this._FECHA_RETIRO != value))
				{
					this.OnFECHA_RETIROChanging(value);
					this.SendPropertyChanging();
					this._FECHA_RETIRO = value;
					this.SendPropertyChanged("FECHA_RETIRO");
					this.OnFECHA_RETIROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_CREA", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USUARIO_CREA
		{
			get
			{
				return this._USUARIO_CREA;
			}
			set
			{
				if ((this._USUARIO_CREA != value))
				{
					this.OnUSUARIO_CREAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_CREA = value;
					this.SendPropertyChanged("USUARIO_CREA");
					this.OnUSUARIO_CREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CREA
		{
			get
			{
				return this._FECHA_CREA;
			}
			set
			{
				if ((this._FECHA_CREA != value))
				{
					this.OnFECHA_CREAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CREA = value;
					this.SendPropertyChanged("FECHA_CREA");
					this.OnFECHA_CREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ACTUALIZA", DbType="VarChar(30)")]
		public string USUARIO_ACTUALIZA
		{
			get
			{
				return this._USUARIO_ACTUALIZA;
			}
			set
			{
				if ((this._USUARIO_ACTUALIZA != value))
				{
					this.OnUSUARIO_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_ACTUALIZA = value;
					this.SendPropertyChanged("USUARIO_ACTUALIZA");
					this.OnUSUARIO_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ACTUALIZA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ACTUALIZA
		{
			get
			{
				return this._FECHA_ACTUALIZA;
			}
			set
			{
				if ((this._FECHA_ACTUALIZA != value))
				{
					this.OnFECHA_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ACTUALIZA = value;
					this.SendPropertyChanged("FECHA_ACTUALIZA");
					this.OnFECHA_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Bit NOT NULL")]
		public bool ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this.OnACTIVOChanging(value);
					this.SendPropertyChanging();
					this._ACTIVO = value;
					this.SendPropertyChanged("ACTIVO");
					this.OnACTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EMPLEADO_TRASLADO", Storage="_TRASLADO", ThisKey="CODIGO_EMPLEADO", OtherKey="CODIGO_TRASLADOS", IsUnique=true, IsForeignKey=false)]
		public TRASLADO TRASLADO
		{
			get
			{
				return this._TRASLADO.Entity;
			}
			set
			{
				TRASLADO previousValue = this._TRASLADO.Entity;
				if (((previousValue != value) 
							|| (this._TRASLADO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRASLADO.Entity = null;
						previousValue.EMPLEADO = null;
					}
					this._TRASLADO.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO = this;
					}
					this.SendPropertyChanged("TRASLADO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTAMENTO_EMPLEADO", Storage="_DEPARTAMENTO1", ThisKey="DEPARTAMENTO", OtherKey="CODIGO_DEPARTAMENTO", IsForeignKey=true)]
		public DEPARTAMENTO DEPARTAMENTO1
		{
			get
			{
				return this._DEPARTAMENTO1.Entity;
			}
			set
			{
				DEPARTAMENTO previousValue = this._DEPARTAMENTO1.Entity;
				if (((previousValue != value) 
							|| (this._DEPARTAMENTO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DEPARTAMENTO1.Entity = null;
						previousValue.EMPLEADO.Remove(this);
					}
					this._DEPARTAMENTO1.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO.Add(this);
						this._DEPARTAMENTO = value.CODIGO_DEPARTAMENTO;
					}
					else
					{
						this._DEPARTAMENTO = default(int);
					}
					this.SendPropertyChanged("DEPARTAMENTO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MUNICIPIO_EMPLEADO", Storage="_MUNICIPIO1", ThisKey="MUNICIPIO", OtherKey="CODIGO_MUNICIPIO", IsForeignKey=true)]
		public MUNICIPIO MUNICIPIO1
		{
			get
			{
				return this._MUNICIPIO1.Entity;
			}
			set
			{
				MUNICIPIO previousValue = this._MUNICIPIO1.Entity;
				if (((previousValue != value) 
							|| (this._MUNICIPIO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MUNICIPIO1.Entity = null;
						previousValue.EMPLEADO.Remove(this);
					}
					this._MUNICIPIO1.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO.Add(this);
						this._MUNICIPIO = value.CODIGO_MUNICIPIO;
					}
					else
					{
						this._MUNICIPIO = default(int);
					}
					this.SendPropertyChanged("MUNICIPIO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_EMPLEADO", Storage="_PAIS1", ThisKey="PAIS", OtherKey="CODIGO_PAIS", IsForeignKey=true)]
		public PAIS PAIS1
		{
			get
			{
				return this._PAIS1.Entity;
			}
			set
			{
				PAIS previousValue = this._PAIS1.Entity;
				if (((previousValue != value) 
							|| (this._PAIS1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PAIS1.Entity = null;
						previousValue.EMPLEADO.Remove(this);
					}
					this._PAIS1.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO.Add(this);
						this._PAIS = value.CODIGO_PAIS;
					}
					else
					{
						this._PAIS = default(int);
					}
					this.SendPropertyChanged("PAIS1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPO_EMPLEADO_EMPLEADO", Storage="_TIPO_EMPLEADO1", ThisKey="TIPO_EMPLEADO", OtherKey="CODIGO_TIPO_EMPLEADO", IsForeignKey=true)]
		public TIPO_EMPLEADO TIPO_EMPLEADO1
		{
			get
			{
				return this._TIPO_EMPLEADO1.Entity;
			}
			set
			{
				TIPO_EMPLEADO previousValue = this._TIPO_EMPLEADO1.Entity;
				if (((previousValue != value) 
							|| (this._TIPO_EMPLEADO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIPO_EMPLEADO1.Entity = null;
						previousValue.EMPLEADO.Remove(this);
					}
					this._TIPO_EMPLEADO1.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO.Add(this);
						this._TIPO_EMPLEADO = value.CODIGO_TIPO_EMPLEADO;
					}
					else
					{
						this._TIPO_EMPLEADO = default(int);
					}
					this.SendPropertyChanged("TIPO_EMPLEADO1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
