#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planillas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PLANILLAS")]
	public partial class DBPlanillasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDEPARTAMENTO(DEPARTAMENTO instance);
    partial void UpdateDEPARTAMENTO(DEPARTAMENTO instance);
    partial void DeleteDEPARTAMENTO(DEPARTAMENTO instance);
    partial void InsertMUNICIPIO(MUNICIPIO instance);
    partial void UpdateMUNICIPIO(MUNICIPIO instance);
    partial void DeleteMUNICIPIO(MUNICIPIO instance);
    partial void InsertPAIS(PAIS instance);
    partial void UpdatePAIS(PAIS instance);
    partial void DeletePAIS(PAIS instance);
    partial void InsertTIPO_EMPLEADO(TIPO_EMPLEADO instance);
    partial void UpdateTIPO_EMPLEADO(TIPO_EMPLEADO instance);
    partial void DeleteTIPO_EMPLEADO(TIPO_EMPLEADO instance);
    partial void InsertEMPLEADO(EMPLEADO instance);
    partial void UpdateEMPLEADO(EMPLEADO instance);
    partial void DeleteEMPLEADO(EMPLEADO instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    partial void InsertAREA(AREA instance);
    partial void UpdateAREA(AREA instance);
    partial void DeleteAREA(AREA instance);
    partial void InsertTRASLADO(TRASLADO instance);
    partial void UpdateTRASLADO(TRASLADO instance);
    partial void DeleteTRASLADO(TRASLADO instance);
    #endregion
		
		public DBPlanillasDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PLANILLASConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBPlanillasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPlanillasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPlanillasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPlanillasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DEPARTAMENTO> DEPARTAMENTO
		{
			get
			{
				return this.GetTable<DEPARTAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<MUNICIPIO> MUNICIPIO
		{
			get
			{
				return this.GetTable<MUNICIPIO>();
			}
		}
		
		public System.Data.Linq.Table<PAIS> PAIS
		{
			get
			{
				return this.GetTable<PAIS>();
			}
		}
		
		public System.Data.Linq.Table<TIPO_EMPLEADO> TIPO_EMPLEADO
		{
			get
			{
				return this.GetTable<TIPO_EMPLEADO>();
			}
		}
		
		public System.Data.Linq.Table<EMPLEADO> EMPLEADO
		{
			get
			{
				return this.GetTable<EMPLEADO>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIO
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<AREA> AREA
		{
			get
			{
				return this.GetTable<AREA>();
			}
		}
		
		public System.Data.Linq.Table<TRASLADO> TRASLADO
		{
			get
			{
				return this.GetTable<TRASLADO>();
			}
		}
		
		public System.Data.Linq.Table<V_TRASLADOS> V_TRASLADOS
		{
			get
			{
				return this.GetTable<V_TRASLADOS>();
			}
		}
		
		public System.Data.Linq.Table<V_EMPLEADOS> V_EMPLEADOS
		{
			get
			{
				return this.GetTable<V_EMPLEADOS>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MTTO_AREAS")]
		public int SP_MTTO_AREAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_AREA", DbType="Int")] System.Nullable<int> cODIGO_AREA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_AREA", DbType="VarChar(50)")] string nOMBRE_AREA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_MODIFICADOR", DbType="Int")] System.Nullable<int> tIPO_MODIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_AREA, nOMBRE_AREA, tIPO_MODIFICADOR);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MTTO_TIPO_EMPLEADO")]
		public int SP_MTTO_TIPO_EMPLEADO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_TIPO_EMPLEADO", DbType="Int")] System.Nullable<int> cODIGO_TIPO_EMPLEADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_TIPO_EMPLEADO", DbType="VarChar(30)")] string nOMBRE_TIPO_EMPLEADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUELDO", DbType="Decimal(12,2)")] System.Nullable<decimal> sUELDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_MODIFICADOR", DbType="Int")] System.Nullable<int> tIPO_MODIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_TIPO_EMPLEADO, nOMBRE_TIPO_EMPLEADO, sUELDO, tIPO_MODIFICADOR);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MTTO_USUARIO")]
		public int SP_MTTO_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_USUARIO", DbType="Int")] System.Nullable<int> cODIGO_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(10)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="VarChar(8)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_MODIFICADOR", DbType="Int")] System.Nullable<int> tIPO_MODIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_USUARIO, nOMBRE, cONTRASENA, tIPO_MODIFICADOR);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DATA_USUARIO")]
		public ISingleResult<SP_DATA_USUARIOResult> SP_DATA_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_USUARIO", DbType="Int")] System.Nullable<int> cODIGO_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(10)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="VarChar(8)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_CONSULTA", DbType="Int")] System.Nullable<int> tIPO_CONSULTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_USUARIO, nOMBRE, cONTRASENA, tIPO_CONSULTA);
			return ((ISingleResult<SP_DATA_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MTTO_TRASLADOS")]
		public int SP_MTTO_TRASLADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_TRASLADOS", DbType="Int")] System.Nullable<int> cODIGO_TRASLADOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_EMPLEADO", DbType="Int")] System.Nullable<int> cODIGO_EMPLEADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_AREA_DESTINO", DbType="Int")] System.Nullable<int> cODIGO_AREA_DESTINO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_TIPO_EMPLEADO_ACTUAL", DbType="Int")] System.Nullable<int> cODIGO_TIPO_EMPLEADO_ACTUAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_TRASLADO", DbType="Date")] System.Nullable<System.DateTime> fECHA_TRASLADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_TRASLADO", DbType="VarChar(2)")] string eSTADO_TRASLADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO_CREA", DbType="VarChar(30)")] string uSUARIO_CREA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO_ACTUALIZA", DbType="VarChar(30)")] string uSUARIO_ACTUALIZA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_MODIFICADOR", DbType="Int")] System.Nullable<int> tIPO_MODIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_TRASLADOS, cODIGO_EMPLEADO, cODIGO_AREA_DESTINO, cODIGO_TIPO_EMPLEADO_ACTUAL, fECHA_TRASLADO, eSTADO_TRASLADO, uSUARIO_CREA, uSUARIO_ACTUALIZA, tIPO_MODIFICADOR);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MTTO_TIPO_EMPLEADO")]
		public int SP_MTTO_TIPO_EMPLEADO1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_TIPO_EMPLEADO", DbType="Int")] System.Nullable<int> cODIGO_TIPO_EMPLEADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_TIPO_EMPLEADO", DbType="VarChar(30)")] string nOMBRE_TIPO_EMPLEADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUELDO", DbType="Decimal(12,2)")] System.Nullable<decimal> sUELDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_MODIFICADOR", DbType="Int")] System.Nullable<int> tIPO_MODIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_TIPO_EMPLEADO, nOMBRE_TIPO_EMPLEADO, sUELDO, tIPO_MODIFICADOR);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MTTO_EMPLEADO")]
		public int SP_MTTO_EMPLEADO(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_EMPLEADO", DbType="Int")] System.Nullable<int> cODIGO_EMPLEADO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRIMER_NOMBRE", DbType="VarChar(50)")] string pRIMER_NOMBRE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEGUNDO_NOMBRE", DbType="VarChar(50)")] string sEGUNDO_NOMBRE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRIMER_APELLIDO", DbType="VarChar(50)")] string pRIMER_APELLIDO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEGUNDO_APELLIDO", DbType="VarChar(50)")] string sEGUNDO_APELLIDO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fECHA_NACIMIENTO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEXO", DbType="Char(1)")] System.Nullable<char> sEXO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PAIS", DbType="Int")] System.Nullable<int> pAIS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEPARTAMENTO", DbType="Int")] System.Nullable<int> dEPARTAMENTO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MUNICIPIO", DbType="Int")] System.Nullable<int> mUNICIPIO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="VarChar(250)")] string dIRECCION, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_CIVIL", DbType="VarChar(2)")] string eSTADO_CIVIL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="VarChar(15)")] string tELEFONO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO_ELECTRONICO", DbType="VarChar(30)")] string cORREO_ELECTRONICO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LUGAR_NACIMIENTO", DbType="VarChar(50)")] string lUGAR_NACIMIENTO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DUI", DbType="VarChar(10)")] string dUI, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NIT", DbType="VarChar(20)")] string nIT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AFP", DbType="VarChar(3)")] string aFP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEGURO", DbType="VarChar(15)")] string sEGURO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUP", DbType="VarChar(15)")] string nUP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_EMPLEADO", DbType="Int")] System.Nullable<int> tIPO_EMPLEADO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_INGRESO", DbType="Date")] System.Nullable<System.DateTime> fECHA_INGRESO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_RETIRO", DbType="Date")] System.Nullable<System.DateTime> fECHA_RETIRO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO_CREA", DbType="VarChar(30)")] string uSUARIO_CREA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO_ACTUALIZA", DbType="VarChar(30)")] string uSUARIO_ACTUALIZA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVO", DbType="Bit")] System.Nullable<bool> aCTIVO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AREA", DbType="Int")] System.Nullable<int> aREA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_MODIFICADOR", DbType="Int")] System.Nullable<int> tIPO_MODIFICADOR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_EMPLEADO, pRIMER_NOMBRE, sEGUNDO_NOMBRE, pRIMER_APELLIDO, sEGUNDO_APELLIDO, fECHA_NACIMIENTO, sEXO, pAIS, dEPARTAMENTO, mUNICIPIO, dIRECCION, eSTADO_CIVIL, tELEFONO, cORREO_ELECTRONICO, lUGAR_NACIMIENTO, dUI, nIT, aFP, sEGURO, nUP, tIPO_EMPLEADO, fECHA_INGRESO, fECHA_RETIRO, uSUARIO_CREA, uSUARIO_ACTUALIZA, aCTIVO, aREA, tIPO_MODIFICADOR);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPARTAMENTO")]
	public partial class DEPARTAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_DEPARTAMENTO;
		
		private string _NOMBRE_DEPARTAMENTO;
		
		private int _PAIS;
		
		private EntitySet<MUNICIPIO> _MUNICIPIO;
		
		private EntitySet<EMPLEADO> _EMPLEADO;
		
		private EntityRef<PAIS> _PAIS1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_DEPARTAMENTOChanging(int value);
    partial void OnCODIGO_DEPARTAMENTOChanged();
    partial void OnNOMBRE_DEPARTAMENTOChanging(string value);
    partial void OnNOMBRE_DEPARTAMENTOChanged();
    partial void OnPAISChanging(int value);
    partial void OnPAISChanged();
    #endregion
		
		public DEPARTAMENTO()
		{
			this._MUNICIPIO = new EntitySet<MUNICIPIO>(new Action<MUNICIPIO>(this.attach_MUNICIPIO), new Action<MUNICIPIO>(this.detach_MUNICIPIO));
			this._EMPLEADO = new EntitySet<EMPLEADO>(new Action<EMPLEADO>(this.attach_EMPLEADO), new Action<EMPLEADO>(this.detach_EMPLEADO));
			this._PAIS1 = default(EntityRef<PAIS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_DEPARTAMENTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_DEPARTAMENTO
		{
			get
			{
				return this._CODIGO_DEPARTAMENTO;
			}
			set
			{
				if ((this._CODIGO_DEPARTAMENTO != value))
				{
					this.OnCODIGO_DEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_DEPARTAMENTO = value;
					this.SendPropertyChanged("CODIGO_DEPARTAMENTO");
					this.OnCODIGO_DEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DEPARTAMENTO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_DEPARTAMENTO
		{
			get
			{
				return this._NOMBRE_DEPARTAMENTO;
			}
			set
			{
				if ((this._NOMBRE_DEPARTAMENTO != value))
				{
					this.OnNOMBRE_DEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_DEPARTAMENTO = value;
					this.SendPropertyChanged("NOMBRE_DEPARTAMENTO");
					this.OnNOMBRE_DEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS", DbType="Int NOT NULL")]
		public int PAIS
		{
			get
			{
				return this._PAIS;
			}
			set
			{
				if ((this._PAIS != value))
				{
					if (this._PAIS1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAISChanging(value);
					this.SendPropertyChanging();
					this._PAIS = value;
					this.SendPropertyChanged("PAIS");
					this.OnPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTAMENTO_MUNICIPIO", Storage="_MUNICIPIO", ThisKey="CODIGO_DEPARTAMENTO", OtherKey="DEPARTAMENTO")]
		public EntitySet<MUNICIPIO> MUNICIPIO
		{
			get
			{
				return this._MUNICIPIO;
			}
			set
			{
				this._MUNICIPIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTAMENTO_EMPLEADO", Storage="_EMPLEADO", ThisKey="CODIGO_DEPARTAMENTO", OtherKey="DEPARTAMENTO")]
		public EntitySet<EMPLEADO> EMPLEADO
		{
			get
			{
				return this._EMPLEADO;
			}
			set
			{
				this._EMPLEADO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_DEPARTAMENTO", Storage="_PAIS1", ThisKey="PAIS", OtherKey="CODIGO_PAIS", IsForeignKey=true)]
		public PAIS PAIS1
		{
			get
			{
				return this._PAIS1.Entity;
			}
			set
			{
				PAIS previousValue = this._PAIS1.Entity;
				if (((previousValue != value) 
							|| (this._PAIS1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PAIS1.Entity = null;
						previousValue.DEPARTAMENTO.Remove(this);
					}
					this._PAIS1.Entity = value;
					if ((value != null))
					{
						value.DEPARTAMENTO.Add(this);
						this._PAIS = value.CODIGO_PAIS;
					}
					else
					{
						this._PAIS = default(int);
					}
					this.SendPropertyChanged("PAIS1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MUNICIPIO(MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTAMENTO1 = this;
		}
		
		private void detach_MUNICIPIO(MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTAMENTO1 = null;
		}
		
		private void attach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTAMENTO1 = this;
		}
		
		private void detach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTAMENTO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MUNICIPIO")]
	public partial class MUNICIPIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_MUNICIPIO;
		
		private string _NOMBRE_MINICIPIO;
		
		private int _PAIS;
		
		private int _DEPARTAMENTO;
		
		private EntitySet<EMPLEADO> _EMPLEADO;
		
		private EntityRef<DEPARTAMENTO> _DEPARTAMENTO1;
		
		private EntityRef<PAIS> _PAIS1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_MUNICIPIOChanging(int value);
    partial void OnCODIGO_MUNICIPIOChanged();
    partial void OnNOMBRE_MINICIPIOChanging(string value);
    partial void OnNOMBRE_MINICIPIOChanged();
    partial void OnPAISChanging(int value);
    partial void OnPAISChanged();
    partial void OnDEPARTAMENTOChanging(int value);
    partial void OnDEPARTAMENTOChanged();
    #endregion
		
		public MUNICIPIO()
		{
			this._EMPLEADO = new EntitySet<EMPLEADO>(new Action<EMPLEADO>(this.attach_EMPLEADO), new Action<EMPLEADO>(this.detach_EMPLEADO));
			this._DEPARTAMENTO1 = default(EntityRef<DEPARTAMENTO>);
			this._PAIS1 = default(EntityRef<PAIS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_MUNICIPIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_MUNICIPIO
		{
			get
			{
				return this._CODIGO_MUNICIPIO;
			}
			set
			{
				if ((this._CODIGO_MUNICIPIO != value))
				{
					this.OnCODIGO_MUNICIPIOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_MUNICIPIO = value;
					this.SendPropertyChanged("CODIGO_MUNICIPIO");
					this.OnCODIGO_MUNICIPIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MINICIPIO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MINICIPIO
		{
			get
			{
				return this._NOMBRE_MINICIPIO;
			}
			set
			{
				if ((this._NOMBRE_MINICIPIO != value))
				{
					this.OnNOMBRE_MINICIPIOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_MINICIPIO = value;
					this.SendPropertyChanged("NOMBRE_MINICIPIO");
					this.OnNOMBRE_MINICIPIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS", DbType="Int NOT NULL")]
		public int PAIS
		{
			get
			{
				return this._PAIS;
			}
			set
			{
				if ((this._PAIS != value))
				{
					if (this._PAIS1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAISChanging(value);
					this.SendPropertyChanging();
					this._PAIS = value;
					this.SendPropertyChanged("PAIS");
					this.OnPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTAMENTO", DbType="Int NOT NULL")]
		public int DEPARTAMENTO
		{
			get
			{
				return this._DEPARTAMENTO;
			}
			set
			{
				if ((this._DEPARTAMENTO != value))
				{
					if (this._DEPARTAMENTO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._DEPARTAMENTO = value;
					this.SendPropertyChanged("DEPARTAMENTO");
					this.OnDEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MUNICIPIO_EMPLEADO", Storage="_EMPLEADO", ThisKey="CODIGO_MUNICIPIO", OtherKey="MUNICIPIO")]
		public EntitySet<EMPLEADO> EMPLEADO
		{
			get
			{
				return this._EMPLEADO;
			}
			set
			{
				this._EMPLEADO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTAMENTO_MUNICIPIO", Storage="_DEPARTAMENTO1", ThisKey="DEPARTAMENTO", OtherKey="CODIGO_DEPARTAMENTO", IsForeignKey=true)]
		public DEPARTAMENTO DEPARTAMENTO1
		{
			get
			{
				return this._DEPARTAMENTO1.Entity;
			}
			set
			{
				DEPARTAMENTO previousValue = this._DEPARTAMENTO1.Entity;
				if (((previousValue != value) 
							|| (this._DEPARTAMENTO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DEPARTAMENTO1.Entity = null;
						previousValue.MUNICIPIO.Remove(this);
					}
					this._DEPARTAMENTO1.Entity = value;
					if ((value != null))
					{
						value.MUNICIPIO.Add(this);
						this._DEPARTAMENTO = value.CODIGO_DEPARTAMENTO;
					}
					else
					{
						this._DEPARTAMENTO = default(int);
					}
					this.SendPropertyChanged("DEPARTAMENTO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_MUNICIPIO", Storage="_PAIS1", ThisKey="PAIS", OtherKey="CODIGO_PAIS", IsForeignKey=true)]
		public PAIS PAIS1
		{
			get
			{
				return this._PAIS1.Entity;
			}
			set
			{
				PAIS previousValue = this._PAIS1.Entity;
				if (((previousValue != value) 
							|| (this._PAIS1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PAIS1.Entity = null;
						previousValue.MUNICIPIO.Remove(this);
					}
					this._PAIS1.Entity = value;
					if ((value != null))
					{
						value.MUNICIPIO.Add(this);
						this._PAIS = value.CODIGO_PAIS;
					}
					else
					{
						this._PAIS = default(int);
					}
					this.SendPropertyChanged("PAIS1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.MUNICIPIO1 = this;
		}
		
		private void detach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.MUNICIPIO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAIS")]
	public partial class PAIS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_PAIS;
		
		private string _NOMBRE_PAIS;
		
		private EntitySet<DEPARTAMENTO> _DEPARTAMENTO;
		
		private EntitySet<MUNICIPIO> _MUNICIPIO;
		
		private EntitySet<EMPLEADO> _EMPLEADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_PAISChanging(int value);
    partial void OnCODIGO_PAISChanged();
    partial void OnNOMBRE_PAISChanging(string value);
    partial void OnNOMBRE_PAISChanged();
    #endregion
		
		public PAIS()
		{
			this._DEPARTAMENTO = new EntitySet<DEPARTAMENTO>(new Action<DEPARTAMENTO>(this.attach_DEPARTAMENTO), new Action<DEPARTAMENTO>(this.detach_DEPARTAMENTO));
			this._MUNICIPIO = new EntitySet<MUNICIPIO>(new Action<MUNICIPIO>(this.attach_MUNICIPIO), new Action<MUNICIPIO>(this.detach_MUNICIPIO));
			this._EMPLEADO = new EntitySet<EMPLEADO>(new Action<EMPLEADO>(this.attach_EMPLEADO), new Action<EMPLEADO>(this.detach_EMPLEADO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PAIS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_PAIS
		{
			get
			{
				return this._CODIGO_PAIS;
			}
			set
			{
				if ((this._CODIGO_PAIS != value))
				{
					this.OnCODIGO_PAISChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_PAIS = value;
					this.SendPropertyChanged("CODIGO_PAIS");
					this.OnCODIGO_PAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PAIS", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string NOMBRE_PAIS
		{
			get
			{
				return this._NOMBRE_PAIS;
			}
			set
			{
				if ((this._NOMBRE_PAIS != value))
				{
					this.OnNOMBRE_PAISChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_PAIS = value;
					this.SendPropertyChanged("NOMBRE_PAIS");
					this.OnNOMBRE_PAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_DEPARTAMENTO", Storage="_DEPARTAMENTO", ThisKey="CODIGO_PAIS", OtherKey="PAIS")]
		public EntitySet<DEPARTAMENTO> DEPARTAMENTO
		{
			get
			{
				return this._DEPARTAMENTO;
			}
			set
			{
				this._DEPARTAMENTO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_MUNICIPIO", Storage="_MUNICIPIO", ThisKey="CODIGO_PAIS", OtherKey="PAIS")]
		public EntitySet<MUNICIPIO> MUNICIPIO
		{
			get
			{
				return this._MUNICIPIO;
			}
			set
			{
				this._MUNICIPIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_EMPLEADO", Storage="_EMPLEADO", ThisKey="CODIGO_PAIS", OtherKey="PAIS")]
		public EntitySet<EMPLEADO> EMPLEADO
		{
			get
			{
				return this._EMPLEADO;
			}
			set
			{
				this._EMPLEADO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DEPARTAMENTO(DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = this;
		}
		
		private void detach_DEPARTAMENTO(DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = null;
		}
		
		private void attach_MUNICIPIO(MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = this;
		}
		
		private void detach_MUNICIPIO(MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = null;
		}
		
		private void attach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = this;
		}
		
		private void detach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.PAIS1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIPO_EMPLEADO")]
	public partial class TIPO_EMPLEADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_TIPO_EMPLEADO;
		
		private string _NOMBRE_TIPO_EMPLEADO;
		
		private decimal _SUELDO;
		
		private EntitySet<EMPLEADO> _EMPLEADO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_TIPO_EMPLEADOChanging(int value);
    partial void OnCODIGO_TIPO_EMPLEADOChanged();
    partial void OnNOMBRE_TIPO_EMPLEADOChanging(string value);
    partial void OnNOMBRE_TIPO_EMPLEADOChanged();
    partial void OnSUELDOChanging(decimal value);
    partial void OnSUELDOChanged();
    #endregion
		
		public TIPO_EMPLEADO()
		{
			this._EMPLEADO = new EntitySet<EMPLEADO>(new Action<EMPLEADO>(this.attach_EMPLEADO), new Action<EMPLEADO>(this.detach_EMPLEADO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TIPO_EMPLEADO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_TIPO_EMPLEADO
		{
			get
			{
				return this._CODIGO_TIPO_EMPLEADO;
			}
			set
			{
				if ((this._CODIGO_TIPO_EMPLEADO != value))
				{
					this.OnCODIGO_TIPO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_TIPO_EMPLEADO = value;
					this.SendPropertyChanged("CODIGO_TIPO_EMPLEADO");
					this.OnCODIGO_TIPO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_TIPO_EMPLEADO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_TIPO_EMPLEADO
		{
			get
			{
				return this._NOMBRE_TIPO_EMPLEADO;
			}
			set
			{
				if ((this._NOMBRE_TIPO_EMPLEADO != value))
				{
					this.OnNOMBRE_TIPO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_TIPO_EMPLEADO = value;
					this.SendPropertyChanged("NOMBRE_TIPO_EMPLEADO");
					this.OnNOMBRE_TIPO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUELDO", DbType="Decimal(12,2) NOT NULL")]
		public decimal SUELDO
		{
			get
			{
				return this._SUELDO;
			}
			set
			{
				if ((this._SUELDO != value))
				{
					this.OnSUELDOChanging(value);
					this.SendPropertyChanging();
					this._SUELDO = value;
					this.SendPropertyChanged("SUELDO");
					this.OnSUELDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPO_EMPLEADO_EMPLEADO", Storage="_EMPLEADO", ThisKey="CODIGO_TIPO_EMPLEADO", OtherKey="TIPO_EMPLEADO")]
		public EntitySet<EMPLEADO> EMPLEADO
		{
			get
			{
				return this._EMPLEADO;
			}
			set
			{
				this._EMPLEADO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.TIPO_EMPLEADO1 = this;
		}
		
		private void detach_EMPLEADO(EMPLEADO entity)
		{
			this.SendPropertyChanging();
			entity.TIPO_EMPLEADO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPLEADO")]
	public partial class EMPLEADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_EMPLEADO;
		
		private string _PRIMER_NOMBRE;
		
		private string _SEGUNDO_NOMBRE;
		
		private string _PRIMER_APELLIDO;
		
		private string _SEGUNDO_APELLIDO;
		
		private System.DateTime _FECHA_NACIMIENTO;
		
		private char _SEXO;
		
		private int _PAIS;
		
		private int _DEPARTAMENTO;
		
		private int _MUNICIPIO;
		
		private string _DIRECCION;
		
		private string _ESTADO_CIVIL;
		
		private string _TELEFONO;
		
		private string _CORREO_ELECTRONICO;
		
		private string _LUGAR_NACIMIENTO;
		
		private string _DUI;
		
		private string _NIT;
		
		private string _AFP;
		
		private string _SEGURO;
		
		private string _NUP;
		
		private int _TIPO_EMPLEADO;
		
		private System.DateTime _FECHA_INGRESO;
		
		private System.DateTime _FECHA_RETIRO;
		
		private string _USUARIO_CREA;
		
		private System.DateTime _FECHA_CREA;
		
		private string _USUARIO_ACTUALIZA;
		
		private System.Nullable<System.DateTime> _FECHA_ACTUALIZA;
		
		private bool _ACTIVO;
		
		private int _AREA;
		
		private EntityRef<DEPARTAMENTO> _DEPARTAMENTO1;
		
		private EntityRef<MUNICIPIO> _MUNICIPIO1;
		
		private EntityRef<PAIS> _PAIS1;
		
		private EntityRef<TIPO_EMPLEADO> _TIPO_EMPLEADO1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_EMPLEADOChanging(int value);
    partial void OnCODIGO_EMPLEADOChanged();
    partial void OnPRIMER_NOMBREChanging(string value);
    partial void OnPRIMER_NOMBREChanged();
    partial void OnSEGUNDO_NOMBREChanging(string value);
    partial void OnSEGUNDO_NOMBREChanged();
    partial void OnPRIMER_APELLIDOChanging(string value);
    partial void OnPRIMER_APELLIDOChanged();
    partial void OnSEGUNDO_APELLIDOChanging(string value);
    partial void OnSEGUNDO_APELLIDOChanged();
    partial void OnFECHA_NACIMIENTOChanging(System.DateTime value);
    partial void OnFECHA_NACIMIENTOChanged();
    partial void OnSEXOChanging(char value);
    partial void OnSEXOChanged();
    partial void OnPAISChanging(int value);
    partial void OnPAISChanged();
    partial void OnDEPARTAMENTOChanging(int value);
    partial void OnDEPARTAMENTOChanged();
    partial void OnMUNICIPIOChanging(int value);
    partial void OnMUNICIPIOChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnESTADO_CIVILChanging(string value);
    partial void OnESTADO_CIVILChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnCORREO_ELECTRONICOChanging(string value);
    partial void OnCORREO_ELECTRONICOChanged();
    partial void OnLUGAR_NACIMIENTOChanging(string value);
    partial void OnLUGAR_NACIMIENTOChanged();
    partial void OnDUIChanging(string value);
    partial void OnDUIChanged();
    partial void OnNITChanging(string value);
    partial void OnNITChanged();
    partial void OnAFPChanging(string value);
    partial void OnAFPChanged();
    partial void OnSEGUROChanging(string value);
    partial void OnSEGUROChanged();
    partial void OnNUPChanging(string value);
    partial void OnNUPChanged();
    partial void OnTIPO_EMPLEADOChanging(int value);
    partial void OnTIPO_EMPLEADOChanged();
    partial void OnFECHA_INGRESOChanging(System.DateTime value);
    partial void OnFECHA_INGRESOChanged();
    partial void OnFECHA_RETIROChanging(System.DateTime value);
    partial void OnFECHA_RETIROChanged();
    partial void OnUSUARIO_CREAChanging(string value);
    partial void OnUSUARIO_CREAChanged();
    partial void OnFECHA_CREAChanging(System.DateTime value);
    partial void OnFECHA_CREAChanged();
    partial void OnUSUARIO_ACTUALIZAChanging(string value);
    partial void OnUSUARIO_ACTUALIZAChanged();
    partial void OnFECHA_ACTUALIZAChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_ACTUALIZAChanged();
    partial void OnACTIVOChanging(bool value);
    partial void OnACTIVOChanged();
    partial void OnAREAChanging(int value);
    partial void OnAREAChanged();
    #endregion
		
		public EMPLEADO()
		{
			this._DEPARTAMENTO1 = default(EntityRef<DEPARTAMENTO>);
			this._MUNICIPIO1 = default(EntityRef<MUNICIPIO>);
			this._PAIS1 = default(EntityRef<PAIS>);
			this._TIPO_EMPLEADO1 = default(EntityRef<TIPO_EMPLEADO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_EMPLEADO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_EMPLEADO
		{
			get
			{
				return this._CODIGO_EMPLEADO;
			}
			set
			{
				if ((this._CODIGO_EMPLEADO != value))
				{
					this.OnCODIGO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_EMPLEADO = value;
					this.SendPropertyChanged("CODIGO_EMPLEADO");
					this.OnCODIGO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMER_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PRIMER_NOMBRE
		{
			get
			{
				return this._PRIMER_NOMBRE;
			}
			set
			{
				if ((this._PRIMER_NOMBRE != value))
				{
					this.OnPRIMER_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._PRIMER_NOMBRE = value;
					this.SendPropertyChanged("PRIMER_NOMBRE");
					this.OnPRIMER_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGUNDO_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SEGUNDO_NOMBRE
		{
			get
			{
				return this._SEGUNDO_NOMBRE;
			}
			set
			{
				if ((this._SEGUNDO_NOMBRE != value))
				{
					this.OnSEGUNDO_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._SEGUNDO_NOMBRE = value;
					this.SendPropertyChanged("SEGUNDO_NOMBRE");
					this.OnSEGUNDO_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMER_APELLIDO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PRIMER_APELLIDO
		{
			get
			{
				return this._PRIMER_APELLIDO;
			}
			set
			{
				if ((this._PRIMER_APELLIDO != value))
				{
					this.OnPRIMER_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._PRIMER_APELLIDO = value;
					this.SendPropertyChanged("PRIMER_APELLIDO");
					this.OnPRIMER_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGUNDO_APELLIDO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SEGUNDO_APELLIDO
		{
			get
			{
				return this._SEGUNDO_APELLIDO;
			}
			set
			{
				if ((this._SEGUNDO_APELLIDO != value))
				{
					this.OnSEGUNDO_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._SEGUNDO_APELLIDO = value;
					this.SendPropertyChanged("SEGUNDO_APELLIDO");
					this.OnSEGUNDO_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this.OnFECHA_NACIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_NACIMIENTO = value;
					this.SendPropertyChanged("FECHA_NACIMIENTO");
					this.OnFECHA_NACIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="Char(1) NOT NULL")]
		public char SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this.OnSEXOChanging(value);
					this.SendPropertyChanging();
					this._SEXO = value;
					this.SendPropertyChanged("SEXO");
					this.OnSEXOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS", DbType="Int NOT NULL")]
		public int PAIS
		{
			get
			{
				return this._PAIS;
			}
			set
			{
				if ((this._PAIS != value))
				{
					if (this._PAIS1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAISChanging(value);
					this.SendPropertyChanging();
					this._PAIS = value;
					this.SendPropertyChanged("PAIS");
					this.OnPAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTAMENTO", DbType="Int NOT NULL")]
		public int DEPARTAMENTO
		{
			get
			{
				return this._DEPARTAMENTO;
			}
			set
			{
				if ((this._DEPARTAMENTO != value))
				{
					if (this._DEPARTAMENTO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._DEPARTAMENTO = value;
					this.SendPropertyChanged("DEPARTAMENTO");
					this.OnDEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUNICIPIO", DbType="Int NOT NULL")]
		public int MUNICIPIO
		{
			get
			{
				return this._MUNICIPIO;
			}
			set
			{
				if ((this._MUNICIPIO != value))
				{
					if (this._MUNICIPIO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMUNICIPIOChanging(value);
					this.SendPropertyChanging();
					this._MUNICIPIO = value;
					this.SendPropertyChanged("MUNICIPIO");
					this.OnMUNICIPIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(250)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_CIVIL", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ESTADO_CIVIL
		{
			get
			{
				return this._ESTADO_CIVIL;
			}
			set
			{
				if ((this._ESTADO_CIVIL != value))
				{
					this.OnESTADO_CIVILChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_CIVIL = value;
					this.SendPropertyChanged("ESTADO_CIVIL");
					this.OnESTADO_CIVILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this.OnCORREO_ELECTRONICOChanging(value);
					this.SendPropertyChanging();
					this._CORREO_ELECTRONICO = value;
					this.SendPropertyChanged("CORREO_ELECTRONICO");
					this.OnCORREO_ELECTRONICOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUGAR_NACIMIENTO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LUGAR_NACIMIENTO
		{
			get
			{
				return this._LUGAR_NACIMIENTO;
			}
			set
			{
				if ((this._LUGAR_NACIMIENTO != value))
				{
					this.OnLUGAR_NACIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._LUGAR_NACIMIENTO = value;
					this.SendPropertyChanged("LUGAR_NACIMIENTO");
					this.OnLUGAR_NACIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DUI
		{
			get
			{
				return this._DUI;
			}
			set
			{
				if ((this._DUI != value))
				{
					this.OnDUIChanging(value);
					this.SendPropertyChanging();
					this._DUI = value;
					this.SendPropertyChanged("DUI");
					this.OnDUIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this.OnNITChanging(value);
					this.SendPropertyChanging();
					this._NIT = value;
					this.SendPropertyChanged("NIT");
					this.OnNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AFP", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string AFP
		{
			get
			{
				return this._AFP;
			}
			set
			{
				if ((this._AFP != value))
				{
					this.OnAFPChanging(value);
					this.SendPropertyChanging();
					this._AFP = value;
					this.SendPropertyChanged("AFP");
					this.OnAFPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGURO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SEGURO
		{
			get
			{
				return this._SEGURO;
			}
			set
			{
				if ((this._SEGURO != value))
				{
					this.OnSEGUROChanging(value);
					this.SendPropertyChanging();
					this._SEGURO = value;
					this.SendPropertyChanged("SEGURO");
					this.OnSEGUROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUP", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NUP
		{
			get
			{
				return this._NUP;
			}
			set
			{
				if ((this._NUP != value))
				{
					this.OnNUPChanging(value);
					this.SendPropertyChanging();
					this._NUP = value;
					this.SendPropertyChanged("NUP");
					this.OnNUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_EMPLEADO", DbType="Int NOT NULL")]
		public int TIPO_EMPLEADO
		{
			get
			{
				return this._TIPO_EMPLEADO;
			}
			set
			{
				if ((this._TIPO_EMPLEADO != value))
				{
					if (this._TIPO_EMPLEADO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTIPO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._TIPO_EMPLEADO = value;
					this.SendPropertyChanged("TIPO_EMPLEADO");
					this.OnTIPO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INGRESO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_INGRESO
		{
			get
			{
				return this._FECHA_INGRESO;
			}
			set
			{
				if ((this._FECHA_INGRESO != value))
				{
					this.OnFECHA_INGRESOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INGRESO = value;
					this.SendPropertyChanged("FECHA_INGRESO");
					this.OnFECHA_INGRESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_RETIRO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_RETIRO
		{
			get
			{
				return this._FECHA_RETIRO;
			}
			set
			{
				if ((this._FECHA_RETIRO != value))
				{
					this.OnFECHA_RETIROChanging(value);
					this.SendPropertyChanging();
					this._FECHA_RETIRO = value;
					this.SendPropertyChanged("FECHA_RETIRO");
					this.OnFECHA_RETIROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_CREA", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USUARIO_CREA
		{
			get
			{
				return this._USUARIO_CREA;
			}
			set
			{
				if ((this._USUARIO_CREA != value))
				{
					this.OnUSUARIO_CREAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_CREA = value;
					this.SendPropertyChanged("USUARIO_CREA");
					this.OnUSUARIO_CREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CREA
		{
			get
			{
				return this._FECHA_CREA;
			}
			set
			{
				if ((this._FECHA_CREA != value))
				{
					this.OnFECHA_CREAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CREA = value;
					this.SendPropertyChanged("FECHA_CREA");
					this.OnFECHA_CREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ACTUALIZA", DbType="VarChar(30)")]
		public string USUARIO_ACTUALIZA
		{
			get
			{
				return this._USUARIO_ACTUALIZA;
			}
			set
			{
				if ((this._USUARIO_ACTUALIZA != value))
				{
					this.OnUSUARIO_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_ACTUALIZA = value;
					this.SendPropertyChanged("USUARIO_ACTUALIZA");
					this.OnUSUARIO_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ACTUALIZA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ACTUALIZA
		{
			get
			{
				return this._FECHA_ACTUALIZA;
			}
			set
			{
				if ((this._FECHA_ACTUALIZA != value))
				{
					this.OnFECHA_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ACTUALIZA = value;
					this.SendPropertyChanged("FECHA_ACTUALIZA");
					this.OnFECHA_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Bit NOT NULL")]
		public bool ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this.OnACTIVOChanging(value);
					this.SendPropertyChanging();
					this._ACTIVO = value;
					this.SendPropertyChanged("ACTIVO");
					this.OnACTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA", DbType="Int NULL")]
		public int AREA
		{
			get
			{
				return this._AREA;
			}
			set
			{
				if ((this._AREA != value))
				{
					this.OnAREAChanging(value);
					this.SendPropertyChanging();
					this._AREA = value;
					this.SendPropertyChanged("AREA");
					this.OnAREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTAMENTO_EMPLEADO", Storage="_DEPARTAMENTO1", ThisKey="DEPARTAMENTO", OtherKey="CODIGO_DEPARTAMENTO", IsForeignKey=true)]
		public DEPARTAMENTO DEPARTAMENTO1
		{
			get
			{
				return this._DEPARTAMENTO1.Entity;
			}
			set
			{
				DEPARTAMENTO previousValue = this._DEPARTAMENTO1.Entity;
				if (((previousValue != value) 
							|| (this._DEPARTAMENTO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DEPARTAMENTO1.Entity = null;
						previousValue.EMPLEADO.Remove(this);
					}
					this._DEPARTAMENTO1.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO.Add(this);
						this._DEPARTAMENTO = value.CODIGO_DEPARTAMENTO;
					}
					else
					{
						this._DEPARTAMENTO = default(int);
					}
					this.SendPropertyChanged("DEPARTAMENTO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MUNICIPIO_EMPLEADO", Storage="_MUNICIPIO1", ThisKey="MUNICIPIO", OtherKey="CODIGO_MUNICIPIO", IsForeignKey=true)]
		public MUNICIPIO MUNICIPIO1
		{
			get
			{
				return this._MUNICIPIO1.Entity;
			}
			set
			{
				MUNICIPIO previousValue = this._MUNICIPIO1.Entity;
				if (((previousValue != value) 
							|| (this._MUNICIPIO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MUNICIPIO1.Entity = null;
						previousValue.EMPLEADO.Remove(this);
					}
					this._MUNICIPIO1.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO.Add(this);
						this._MUNICIPIO = value.CODIGO_MUNICIPIO;
					}
					else
					{
						this._MUNICIPIO = default(int);
					}
					this.SendPropertyChanged("MUNICIPIO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PAIS_EMPLEADO", Storage="_PAIS1", ThisKey="PAIS", OtherKey="CODIGO_PAIS", IsForeignKey=true)]
		public PAIS PAIS1
		{
			get
			{
				return this._PAIS1.Entity;
			}
			set
			{
				PAIS previousValue = this._PAIS1.Entity;
				if (((previousValue != value) 
							|| (this._PAIS1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PAIS1.Entity = null;
						previousValue.EMPLEADO.Remove(this);
					}
					this._PAIS1.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO.Add(this);
						this._PAIS = value.CODIGO_PAIS;
					}
					else
					{
						this._PAIS = default(int);
					}
					this.SendPropertyChanged("PAIS1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPO_EMPLEADO_EMPLEADO", Storage="_TIPO_EMPLEADO1", ThisKey="TIPO_EMPLEADO", OtherKey="CODIGO_TIPO_EMPLEADO", IsForeignKey=true)]
		public TIPO_EMPLEADO TIPO_EMPLEADO1
		{
			get
			{
				return this._TIPO_EMPLEADO1.Entity;
			}
			set
			{
				TIPO_EMPLEADO previousValue = this._TIPO_EMPLEADO1.Entity;
				if (((previousValue != value) 
							|| (this._TIPO_EMPLEADO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIPO_EMPLEADO1.Entity = null;
						previousValue.EMPLEADO.Remove(this);
					}
					this._TIPO_EMPLEADO1.Entity = value;
					if ((value != null))
					{
						value.EMPLEADO.Add(this);
						this._TIPO_EMPLEADO = value.CODIGO_TIPO_EMPLEADO;
					}
					else
					{
						this._TIPO_EMPLEADO = default(int);
					}
					this.SendPropertyChanged("TIPO_EMPLEADO1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_USUARIO;
		
		private string _NOMBRE;
		
		private string _CONTRASENA;
		
		private System.DateTime _FECHA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_USUARIOChanging(int value);
    partial void OnCODIGO_USUARIOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnCONTRASENAChanging(string value);
    partial void OnCONTRASENAChanged();
    partial void OnFECHAChanging(System.DateTime value);
    partial void OnFECHAChanged();
    #endregion
		
		public USUARIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_USUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_USUARIO
		{
			get
			{
				return this._CODIGO_USUARIO;
			}
			set
			{
				if ((this._CODIGO_USUARIO != value))
				{
					this.OnCODIGO_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_USUARIO = value;
					this.SendPropertyChanged("CODIGO_USUARIO");
					this.OnCODIGO_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRASENA", DbType="VarChar(500) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CONTRASENA
		{
			get
			{
				return this._CONTRASENA;
			}
			set
			{
				if ((this._CONTRASENA != value))
				{
					this.OnCONTRASENAChanging(value);
					this.SendPropertyChanging();
					this._CONTRASENA = value;
					this.SendPropertyChanged("CONTRASENA");
					this.OnCONTRASENAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="Date NOT NULL")]
		public System.DateTime FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AREA")]
	public partial class AREA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_AREA;
		
		private string _NOMBRE_AREA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_AREAChanging(int value);
    partial void OnCODIGO_AREAChanged();
    partial void OnNOMBRE_AREAChanging(string value);
    partial void OnNOMBRE_AREAChanged();
    #endregion
		
		public AREA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_AREA
		{
			get
			{
				return this._CODIGO_AREA;
			}
			set
			{
				if ((this._CODIGO_AREA != value))
				{
					this.OnCODIGO_AREAChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_AREA = value;
					this.SendPropertyChanged("CODIGO_AREA");
					this.OnCODIGO_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_AREA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_AREA
		{
			get
			{
				return this._NOMBRE_AREA;
			}
			set
			{
				if ((this._NOMBRE_AREA != value))
				{
					this.OnNOMBRE_AREAChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_AREA = value;
					this.SendPropertyChanged("NOMBRE_AREA");
					this.OnNOMBRE_AREAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRASLADO")]
	public partial class TRASLADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODIGO_TRASLADOS;
		
		private int _CODIGO_EMPLEADO;
		
		private int _CODIGO_AREA_ORIGEN;
		
		private int _CODIGO_AREA_DESTINO;
		
		private int _CODIGO_TIPO_EMPLEADO_ANTERIOR;
		
		private int _CODIGO_TIPO_EMPLEADO_ACTUAL;
		
		private string _ESTADO_TRASLADO;
		
		private System.DateTime _FECHA_TRASLADO;
		
		private System.DateTime _USUARIO_CREA;
		
		private System.DateTime _FECHA_CREA;
		
		private string _USUARIO_ACTUALIZA;
		
		private System.DateTime _FECHA_ACTUALIZA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODIGO_TRASLADOSChanging(int value);
    partial void OnCODIGO_TRASLADOSChanged();
    partial void OnCODIGO_EMPLEADOChanging(int value);
    partial void OnCODIGO_EMPLEADOChanged();
    partial void OnCODIGO_AREA_ORIGENChanging(int value);
    partial void OnCODIGO_AREA_ORIGENChanged();
    partial void OnCODIGO_AREA_DESTINOChanging(int value);
    partial void OnCODIGO_AREA_DESTINOChanged();
    partial void OnCODIGO_TIPO_EMPLEADO_ANTERIORChanging(int value);
    partial void OnCODIGO_TIPO_EMPLEADO_ANTERIORChanged();
    partial void OnCODIGO_TIPO_EMPLEADO_ACTUALChanging(int value);
    partial void OnCODIGO_TIPO_EMPLEADO_ACTUALChanged();
    partial void OnESTADO_TRASLADOChanging(string value);
    partial void OnESTADO_TRASLADOChanged();
    partial void OnFECHA_TRASLADOChanging(System.DateTime value);
    partial void OnFECHA_TRASLADOChanged();
    partial void OnUSUARIO_CREAChanging(System.DateTime value);
    partial void OnUSUARIO_CREAChanged();
    partial void OnFECHA_CREAChanging(System.DateTime value);
    partial void OnFECHA_CREAChanged();
    partial void OnUSUARIO_ACTUALIZAChanging(string value);
    partial void OnUSUARIO_ACTUALIZAChanged();
    partial void OnFECHA_ACTUALIZAChanging(System.DateTime value);
    partial void OnFECHA_ACTUALIZAChanged();
    #endregion
		
		public TRASLADO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TRASLADOS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODIGO_TRASLADOS
		{
			get
			{
				return this._CODIGO_TRASLADOS;
			}
			set
			{
				if ((this._CODIGO_TRASLADOS != value))
				{
					this.OnCODIGO_TRASLADOSChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_TRASLADOS = value;
					this.SendPropertyChanged("CODIGO_TRASLADOS");
					this.OnCODIGO_TRASLADOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_EMPLEADO", DbType="Int NOT NULL")]
		public int CODIGO_EMPLEADO
		{
			get
			{
				return this._CODIGO_EMPLEADO;
			}
			set
			{
				if ((this._CODIGO_EMPLEADO != value))
				{
					this.OnCODIGO_EMPLEADOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_EMPLEADO = value;
					this.SendPropertyChanged("CODIGO_EMPLEADO");
					this.OnCODIGO_EMPLEADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA_ORIGEN", DbType="Int NOT NULL")]
		public int CODIGO_AREA_ORIGEN
		{
			get
			{
				return this._CODIGO_AREA_ORIGEN;
			}
			set
			{
				if ((this._CODIGO_AREA_ORIGEN != value))
				{
					this.OnCODIGO_AREA_ORIGENChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_AREA_ORIGEN = value;
					this.SendPropertyChanged("CODIGO_AREA_ORIGEN");
					this.OnCODIGO_AREA_ORIGENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA_DESTINO", DbType="Int NOT NULL")]
		public int CODIGO_AREA_DESTINO
		{
			get
			{
				return this._CODIGO_AREA_DESTINO;
			}
			set
			{
				if ((this._CODIGO_AREA_DESTINO != value))
				{
					this.OnCODIGO_AREA_DESTINOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_AREA_DESTINO = value;
					this.SendPropertyChanged("CODIGO_AREA_DESTINO");
					this.OnCODIGO_AREA_DESTINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TIPO_EMPLEADO_ANTERIOR", DbType="Int NOT NULL")]
		public int CODIGO_TIPO_EMPLEADO_ANTERIOR
		{
			get
			{
				return this._CODIGO_TIPO_EMPLEADO_ANTERIOR;
			}
			set
			{
				if ((this._CODIGO_TIPO_EMPLEADO_ANTERIOR != value))
				{
					this.OnCODIGO_TIPO_EMPLEADO_ANTERIORChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_TIPO_EMPLEADO_ANTERIOR = value;
					this.SendPropertyChanged("CODIGO_TIPO_EMPLEADO_ANTERIOR");
					this.OnCODIGO_TIPO_EMPLEADO_ANTERIORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TIPO_EMPLEADO_ACTUAL", DbType="Int NOT NULL")]
		public int CODIGO_TIPO_EMPLEADO_ACTUAL
		{
			get
			{
				return this._CODIGO_TIPO_EMPLEADO_ACTUAL;
			}
			set
			{
				if ((this._CODIGO_TIPO_EMPLEADO_ACTUAL != value))
				{
					this.OnCODIGO_TIPO_EMPLEADO_ACTUALChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_TIPO_EMPLEADO_ACTUAL = value;
					this.SendPropertyChanged("CODIGO_TIPO_EMPLEADO_ACTUAL");
					this.OnCODIGO_TIPO_EMPLEADO_ACTUALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_TRASLADO", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ESTADO_TRASLADO
		{
			get
			{
				return this._ESTADO_TRASLADO;
			}
			set
			{
				if ((this._ESTADO_TRASLADO != value))
				{
					this.OnESTADO_TRASLADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_TRASLADO = value;
					this.SendPropertyChanged("ESTADO_TRASLADO");
					this.OnESTADO_TRASLADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TRASLADO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_TRASLADO
		{
			get
			{
				return this._FECHA_TRASLADO;
			}
			set
			{
				if ((this._FECHA_TRASLADO != value))
				{
					this.OnFECHA_TRASLADOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_TRASLADO = value;
					this.SendPropertyChanged("FECHA_TRASLADO");
					this.OnFECHA_TRASLADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_CREA", DbType="DateTime NOT NULL")]
		public System.DateTime USUARIO_CREA
		{
			get
			{
				return this._USUARIO_CREA;
			}
			set
			{
				if ((this._USUARIO_CREA != value))
				{
					this.OnUSUARIO_CREAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_CREA = value;
					this.SendPropertyChanged("USUARIO_CREA");
					this.OnUSUARIO_CREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CREA
		{
			get
			{
				return this._FECHA_CREA;
			}
			set
			{
				if ((this._FECHA_CREA != value))
				{
					this.OnFECHA_CREAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CREA = value;
					this.SendPropertyChanged("FECHA_CREA");
					this.OnFECHA_CREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ACTUALIZA", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USUARIO_ACTUALIZA
		{
			get
			{
				return this._USUARIO_ACTUALIZA;
			}
			set
			{
				if ((this._USUARIO_ACTUALIZA != value))
				{
					this.OnUSUARIO_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_ACTUALIZA = value;
					this.SendPropertyChanged("USUARIO_ACTUALIZA");
					this.OnUSUARIO_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ACTUALIZA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_ACTUALIZA
		{
			get
			{
				return this._FECHA_ACTUALIZA;
			}
			set
			{
				if ((this._FECHA_ACTUALIZA != value))
				{
					this.OnFECHA_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ACTUALIZA = value;
					this.SendPropertyChanged("FECHA_ACTUALIZA");
					this.OnFECHA_ACTUALIZAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_TRASLADOS")]
	public partial class V_TRASLADOS
	{
		
		private int _CODIGO_TRASLADOS;
		
		private int _CODIGO_EMPLEADO;
		
		private int _CODIGO_AREA_ORIGEN;
		
		private int _CODIGO_AREA_DESTINO;
		
		private int _CODIGO_TIPO_EMPLEADO_ANTERIOR;
		
		private int _CODIGO_TIPO_EMPLEADO_ACTUAL;
		
		private string _NOMBRE_EMPLEADO;
		
		private string _NOMBRE_AREA_ORIGEN;
		
		private string _NOMBRE_AREA_DESTINO;
		
		private string _NOMBRE_TIPO_EMPLEADO_ORIGEN;
		
		private decimal _SUELDO_ANTERIOR;
		
		private string _NOMBRE_TIPO_EMPLEADO_DESTINO;
		
		private decimal _SUELDO_ACTUAL;
		
		private string _ESTADO_TRASLADO;
		
		private System.DateTime _FECHA_TRASLADO;
		
		private string _USUARIO_CREA;
		
		private System.DateTime _FECHA_CREA;
		
		private string _USUARIO_ACTUALIZA;
		
		private System.Nullable<System.DateTime> _FECHA_ACTUALIZA;
		
		public V_TRASLADOS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TRASLADOS", DbType="Int NOT NULL")]
		public int CODIGO_TRASLADOS
		{
			get
			{
				return this._CODIGO_TRASLADOS;
			}
			set
			{
				if ((this._CODIGO_TRASLADOS != value))
				{
					this._CODIGO_TRASLADOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_EMPLEADO", DbType="Int NOT NULL")]
		public int CODIGO_EMPLEADO
		{
			get
			{
				return this._CODIGO_EMPLEADO;
			}
			set
			{
				if ((this._CODIGO_EMPLEADO != value))
				{
					this._CODIGO_EMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA_ORIGEN", DbType="Int NOT NULL")]
		public int CODIGO_AREA_ORIGEN
		{
			get
			{
				return this._CODIGO_AREA_ORIGEN;
			}
			set
			{
				if ((this._CODIGO_AREA_ORIGEN != value))
				{
					this._CODIGO_AREA_ORIGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA_DESTINO", DbType="Int NOT NULL")]
		public int CODIGO_AREA_DESTINO
		{
			get
			{
				return this._CODIGO_AREA_DESTINO;
			}
			set
			{
				if ((this._CODIGO_AREA_DESTINO != value))
				{
					this._CODIGO_AREA_DESTINO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TIPO_EMPLEADO_ANTERIOR", DbType="Int NOT NULL")]
		public int CODIGO_TIPO_EMPLEADO_ANTERIOR
		{
			get
			{
				return this._CODIGO_TIPO_EMPLEADO_ANTERIOR;
			}
			set
			{
				if ((this._CODIGO_TIPO_EMPLEADO_ANTERIOR != value))
				{
					this._CODIGO_TIPO_EMPLEADO_ANTERIOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_TIPO_EMPLEADO_ACTUAL", DbType="Int NOT NULL")]
		public int CODIGO_TIPO_EMPLEADO_ACTUAL
		{
			get
			{
				return this._CODIGO_TIPO_EMPLEADO_ACTUAL;
			}
			set
			{
				if ((this._CODIGO_TIPO_EMPLEADO_ACTUAL != value))
				{
					this._CODIGO_TIPO_EMPLEADO_ACTUAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_EMPLEADO", DbType="VarChar(112)")]
		public string NOMBRE_EMPLEADO
		{
			get
			{
				return this._NOMBRE_EMPLEADO;
			}
			set
			{
				if ((this._NOMBRE_EMPLEADO != value))
				{
					this._NOMBRE_EMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_AREA_ORIGEN", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_AREA_ORIGEN
		{
			get
			{
				return this._NOMBRE_AREA_ORIGEN;
			}
			set
			{
				if ((this._NOMBRE_AREA_ORIGEN != value))
				{
					this._NOMBRE_AREA_ORIGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_AREA_DESTINO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_AREA_DESTINO
		{
			get
			{
				return this._NOMBRE_AREA_DESTINO;
			}
			set
			{
				if ((this._NOMBRE_AREA_DESTINO != value))
				{
					this._NOMBRE_AREA_DESTINO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_TIPO_EMPLEADO_ORIGEN", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_TIPO_EMPLEADO_ORIGEN
		{
			get
			{
				return this._NOMBRE_TIPO_EMPLEADO_ORIGEN;
			}
			set
			{
				if ((this._NOMBRE_TIPO_EMPLEADO_ORIGEN != value))
				{
					this._NOMBRE_TIPO_EMPLEADO_ORIGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUELDO_ANTERIOR", DbType="Decimal(12,2) NOT NULL")]
		public decimal SUELDO_ANTERIOR
		{
			get
			{
				return this._SUELDO_ANTERIOR;
			}
			set
			{
				if ((this._SUELDO_ANTERIOR != value))
				{
					this._SUELDO_ANTERIOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_TIPO_EMPLEADO_DESTINO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_TIPO_EMPLEADO_DESTINO
		{
			get
			{
				return this._NOMBRE_TIPO_EMPLEADO_DESTINO;
			}
			set
			{
				if ((this._NOMBRE_TIPO_EMPLEADO_DESTINO != value))
				{
					this._NOMBRE_TIPO_EMPLEADO_DESTINO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUELDO_ACTUAL", DbType="Decimal(12,2) NOT NULL")]
		public decimal SUELDO_ACTUAL
		{
			get
			{
				return this._SUELDO_ACTUAL;
			}
			set
			{
				if ((this._SUELDO_ACTUAL != value))
				{
					this._SUELDO_ACTUAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_TRASLADO", DbType="VarChar(10)")]
		public string ESTADO_TRASLADO
		{
			get
			{
				return this._ESTADO_TRASLADO;
			}
			set
			{
				if ((this._ESTADO_TRASLADO != value))
				{
					this._ESTADO_TRASLADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TRASLADO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_TRASLADO
		{
			get
			{
				return this._FECHA_TRASLADO;
			}
			set
			{
				if ((this._FECHA_TRASLADO != value))
				{
					this._FECHA_TRASLADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_CREA", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USUARIO_CREA
		{
			get
			{
				return this._USUARIO_CREA;
			}
			set
			{
				if ((this._USUARIO_CREA != value))
				{
					this._USUARIO_CREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CREA
		{
			get
			{
				return this._FECHA_CREA;
			}
			set
			{
				if ((this._FECHA_CREA != value))
				{
					this._FECHA_CREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ACTUALIZA", DbType="VarChar(30)")]
		public string USUARIO_ACTUALIZA
		{
			get
			{
				return this._USUARIO_ACTUALIZA;
			}
			set
			{
				if ((this._USUARIO_ACTUALIZA != value))
				{
					this._USUARIO_ACTUALIZA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ACTUALIZA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ACTUALIZA
		{
			get
			{
				return this._FECHA_ACTUALIZA;
			}
			set
			{
				if ((this._FECHA_ACTUALIZA != value))
				{
					this._FECHA_ACTUALIZA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_EMPLEADOS")]
	public partial class V_EMPLEADOS
	{
		
		private int _CODIGO_EMPLEADO;
		
		private string _PRIMER_NOMBRE;
		
		private string _SEGUNDO_NOMBRE;
		
		private string _PRIMER_APELLIDO;
		
		private string _SEGUNDO_APELLIDO;
		
		private string _NOMBRE_EMPLEADO;
		
		private System.DateTime _FECHA_NACIMIENTO;
		
		private char _SEXO;
		
		private string _NOMBRE_SEXO;
		
		private int _PAIS;
		
		private string _NOMBRE_PAIS;
		
		private int _DEPARTAMENTO;
		
		private string _NOMBRE_DEPARTAMENTO;
		
		private int _MUNICIPIO;
		
		private string _NOMBRE_MINICIPIO;
		
		private string _DIRECCION;
		
		private string _ESTADO_CIVIL;
		
		private string _NOMBRE_ESTADO_CIVIL;
		
		private string _TELEFONO;
		
		private string _CORREO_ELECTRONICO;
		
		private string _LUGAR_NACIMIENTO;
		
		private string _DUI;
		
		private string _NIT;
		
		private string _AFP;
		
		private string _NOMBRE_AFP;
		
		private string _SEGURO;
		
		private string _NUP;
		
		private int _TIPO_EMPLEADO;
		
		private string _NOMBRE_TIPO_EMPLEADO;
		
		private System.DateTime _FECHA_INGRESO;
		
		private System.DateTime _FECHA_RETIRO;
		
		private string _USUARIO_CREA;
		
		private System.DateTime _FECHA_CREA;
		
		private string _USUARIO_ACTUALIZA;
		
		private System.Nullable<System.DateTime> _FECHA_ACTUALIZA;
		
		private bool _ACTIVO;
		
		private string _NOMBRE_AREA;
		
		private System.Nullable<int> _AREA;
		
		public V_EMPLEADOS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_EMPLEADO", DbType="Int NOT NULL")]
		public int CODIGO_EMPLEADO
		{
			get
			{
				return this._CODIGO_EMPLEADO;
			}
			set
			{
				if ((this._CODIGO_EMPLEADO != value))
				{
					this._CODIGO_EMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMER_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PRIMER_NOMBRE
		{
			get
			{
				return this._PRIMER_NOMBRE;
			}
			set
			{
				if ((this._PRIMER_NOMBRE != value))
				{
					this._PRIMER_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGUNDO_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SEGUNDO_NOMBRE
		{
			get
			{
				return this._SEGUNDO_NOMBRE;
			}
			set
			{
				if ((this._SEGUNDO_NOMBRE != value))
				{
					this._SEGUNDO_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMER_APELLIDO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PRIMER_APELLIDO
		{
			get
			{
				return this._PRIMER_APELLIDO;
			}
			set
			{
				if ((this._PRIMER_APELLIDO != value))
				{
					this._PRIMER_APELLIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGUNDO_APELLIDO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SEGUNDO_APELLIDO
		{
			get
			{
				return this._SEGUNDO_APELLIDO;
			}
			set
			{
				if ((this._SEGUNDO_APELLIDO != value))
				{
					this._SEGUNDO_APELLIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_EMPLEADO", DbType="VarChar(203) NOT NULL", CanBeNull=false)]
		public string NOMBRE_EMPLEADO
		{
			get
			{
				return this._NOMBRE_EMPLEADO;
			}
			set
			{
				if ((this._NOMBRE_EMPLEADO != value))
				{
					this._NOMBRE_EMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this._FECHA_NACIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="Char(1) NOT NULL")]
		public char SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this._SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_SEXO", DbType="VarChar(9)")]
		public string NOMBRE_SEXO
		{
			get
			{
				return this._NOMBRE_SEXO;
			}
			set
			{
				if ((this._NOMBRE_SEXO != value))
				{
					this._NOMBRE_SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS", DbType="Int NOT NULL")]
		public int PAIS
		{
			get
			{
				return this._PAIS;
			}
			set
			{
				if ((this._PAIS != value))
				{
					this._PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PAIS", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string NOMBRE_PAIS
		{
			get
			{
				return this._NOMBRE_PAIS;
			}
			set
			{
				if ((this._NOMBRE_PAIS != value))
				{
					this._NOMBRE_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTAMENTO", DbType="Int NOT NULL")]
		public int DEPARTAMENTO
		{
			get
			{
				return this._DEPARTAMENTO;
			}
			set
			{
				if ((this._DEPARTAMENTO != value))
				{
					this._DEPARTAMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DEPARTAMENTO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_DEPARTAMENTO
		{
			get
			{
				return this._NOMBRE_DEPARTAMENTO;
			}
			set
			{
				if ((this._NOMBRE_DEPARTAMENTO != value))
				{
					this._NOMBRE_DEPARTAMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUNICIPIO", DbType="Int NOT NULL")]
		public int MUNICIPIO
		{
			get
			{
				return this._MUNICIPIO;
			}
			set
			{
				if ((this._MUNICIPIO != value))
				{
					this._MUNICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MINICIPIO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_MINICIPIO
		{
			get
			{
				return this._NOMBRE_MINICIPIO;
			}
			set
			{
				if ((this._NOMBRE_MINICIPIO != value))
				{
					this._NOMBRE_MINICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(250)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_CIVIL", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ESTADO_CIVIL
		{
			get
			{
				return this._ESTADO_CIVIL;
			}
			set
			{
				if ((this._ESTADO_CIVIL != value))
				{
					this._ESTADO_CIVIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_ESTADO_CIVIL", DbType="VarChar(10)")]
		public string NOMBRE_ESTADO_CIVIL
		{
			get
			{
				return this._NOMBRE_ESTADO_CIVIL;
			}
			set
			{
				if ((this._NOMBRE_ESTADO_CIVIL != value))
				{
					this._NOMBRE_ESTADO_CIVIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ELECTRONICO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CORREO_ELECTRONICO
		{
			get
			{
				return this._CORREO_ELECTRONICO;
			}
			set
			{
				if ((this._CORREO_ELECTRONICO != value))
				{
					this._CORREO_ELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUGAR_NACIMIENTO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LUGAR_NACIMIENTO
		{
			get
			{
				return this._LUGAR_NACIMIENTO;
			}
			set
			{
				if ((this._LUGAR_NACIMIENTO != value))
				{
					this._LUGAR_NACIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DUI
		{
			get
			{
				return this._DUI;
			}
			set
			{
				if ((this._DUI != value))
				{
					this._DUI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this._NIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AFP", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string AFP
		{
			get
			{
				return this._AFP;
			}
			set
			{
				if ((this._AFP != value))
				{
					this._AFP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_AFP", DbType="VarChar(6)")]
		public string NOMBRE_AFP
		{
			get
			{
				return this._NOMBRE_AFP;
			}
			set
			{
				if ((this._NOMBRE_AFP != value))
				{
					this._NOMBRE_AFP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGURO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SEGURO
		{
			get
			{
				return this._SEGURO;
			}
			set
			{
				if ((this._SEGURO != value))
				{
					this._SEGURO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUP", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NUP
		{
			get
			{
				return this._NUP;
			}
			set
			{
				if ((this._NUP != value))
				{
					this._NUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_EMPLEADO", DbType="Int NOT NULL")]
		public int TIPO_EMPLEADO
		{
			get
			{
				return this._TIPO_EMPLEADO;
			}
			set
			{
				if ((this._TIPO_EMPLEADO != value))
				{
					this._TIPO_EMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_TIPO_EMPLEADO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOMBRE_TIPO_EMPLEADO
		{
			get
			{
				return this._NOMBRE_TIPO_EMPLEADO;
			}
			set
			{
				if ((this._NOMBRE_TIPO_EMPLEADO != value))
				{
					this._NOMBRE_TIPO_EMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INGRESO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_INGRESO
		{
			get
			{
				return this._FECHA_INGRESO;
			}
			set
			{
				if ((this._FECHA_INGRESO != value))
				{
					this._FECHA_INGRESO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_RETIRO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_RETIRO
		{
			get
			{
				return this._FECHA_RETIRO;
			}
			set
			{
				if ((this._FECHA_RETIRO != value))
				{
					this._FECHA_RETIRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_CREA", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USUARIO_CREA
		{
			get
			{
				return this._USUARIO_CREA;
			}
			set
			{
				if ((this._USUARIO_CREA != value))
				{
					this._USUARIO_CREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CREA
		{
			get
			{
				return this._FECHA_CREA;
			}
			set
			{
				if ((this._FECHA_CREA != value))
				{
					this._FECHA_CREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ACTUALIZA", DbType="VarChar(30)")]
		public string USUARIO_ACTUALIZA
		{
			get
			{
				return this._USUARIO_ACTUALIZA;
			}
			set
			{
				if ((this._USUARIO_ACTUALIZA != value))
				{
					this._USUARIO_ACTUALIZA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ACTUALIZA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ACTUALIZA
		{
			get
			{
				return this._FECHA_ACTUALIZA;
			}
			set
			{
				if ((this._FECHA_ACTUALIZA != value))
				{
					this._FECHA_ACTUALIZA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Bit NOT NULL")]
		public bool ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_AREA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_AREA
		{
			get
			{
				return this._NOMBRE_AREA;
			}
			set
			{
				if ((this._NOMBRE_AREA != value))
				{
					this._NOMBRE_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA", DbType="Int")]
		public System.Nullable<int> AREA
		{
			get
			{
				return this._AREA;
			}
			set
			{
				if ((this._AREA != value))
				{
					this._AREA = value;
				}
			}
		}
	}
	
	public partial class SP_DATA_USUARIOResult
	{
		
		private int _CODIGO_USUARIO;
		
		private string _NOMBRE;
		
		private string _CONTRASENA;
		
		public SP_DATA_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_USUARIO", DbType="Int NOT NULL")]
		public int CODIGO_USUARIO
		{
			get
			{
				return this._CODIGO_USUARIO;
			}
			set
			{
				if ((this._CODIGO_USUARIO != value))
				{
					this._CODIGO_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRASENA", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string CONTRASENA
		{
			get
			{
				return this._CONTRASENA;
			}
			set
			{
				if ((this._CONTRASENA != value))
				{
					this._CONTRASENA = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
